### ISSUE TITLE
Documentation Bug--JSON conversion

### ISSUE THREAD

**Issue by mfreeman-xtivia** [dizitart/nitrite-database#100]
The documentation section that describes how to convert from a JSON string to a Document is out of date and no longer even compiles on version 3.x. 

When I dropped back to version 2.x the conversion compiles as per the documentation.

**Comment by anidotnet** [comment]
Yes you are right. We refactored the `NitriteMapper` interface and missed this documentation.

Here is the actual working code for 3.x

```java
String json = "{\"key1\":1,\"key2\":\"xyz\",\"key3\":1534049285073}";
MapperFacade facade = new JacksonFacade();
Document document = facade.parse(json);
```

**Comment by anidotnet** [comment]
The documentation is also updated - https://www.dizitart.org/nitrite-database/#document
