### ISSUE TITLE
ObjectRepository object id

### ISSUE THREAD

**Issue by dustin-auby** [dizitart/nitrite-database#102]
Hi, when using an ObjectRepository with a mapped object how can i get the NitriteId for an object. i have checked the documentation and can only find an example of getting the id from a Document not a Object.

**Comment by anidotnet** [comment]
Here you go - [NitriteIdAsIdTest](https://github.com/dizitart/nitrite-database/blob/master/nitrite/src/test/java/org/dizitart/no2/objects/NitriteIdAsIdTest.java)

**Comment by dustin-auby** [comment]
Thanks i will do that. while i was playing around i tried adding a variable called _id to the object to test what happens and it mapped the id correctly . would this be a bad idea to use ?

**Comment by anidotnet** [comment]
I'll suggest not to depend on database internals. If some day the default id key is changed to something else say *$id*, then your code will break after upgrading nitrite verson.

**Comment by dustin-auby** [comment]
Ok thanks, will the method you are using not cause a performance issue though as you are generating an id twice ? i could be inserting thousands of rows at times.

**Comment by anidotnet** [comment]
I am not generating id twice, just reusing what is there in collection. There would not be any performance impact as far as I think, though you can confirm it by creating a stress test yourself.

**Comment by dustin-auby** [comment]
there was a slight drop but its negligible when inserting 10000 records it took 14.1 seconds and with the addition it took 15.5 seconds. these were quite big reccords
