### ISSUE TITLE
Problems running datagate docker image 1.0.1

### ISSUE THREAD

**Issue by ariel-lenis** [dizitart/nitrite-database#11]
Hi,

I'm will simplify the problem, lets try to run the 1.0 docker image of datagate and enter to the command line:

![image](https://cloud.githubusercontent.com/assets/27330468/26750587/d989e5d2-47f4-11e7-94d5-51b7aea8e777.png)

But if you try this using the 1.0.1 docker image of datagate we have a problem!:

![image](https://cloud.githubusercontent.com/assets/27330468/26750596/2e2866fe-47f5-11e7-9aea-8d08d273d2fe.png)

**Comment by anidotnet** [comment]
I tried it in my machine and it is working as expected

![image](https://cloud.githubusercontent.com/assets/696662/26750736/0b3dab16-4847-11e7-946d-e3d61b3f6584.png)

Can you try with deleting all previous images and containers from your local?

**Comment by ariel-lenis** [comment]
Yes, my bad

I used this commands to clean all:

```
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
docker rmi $(docker images -a -q)
```

Sorry! next time i will run try this before create a new issue.

**Comment by anidotnet** [comment]
No problems.. It happens.. :)
