### ISSUE TITLE
MethodHandle.invokeExact are only supported starting with Android O

### ISSUE THREAD

**Issue by dustin-auby** [dizitart/nitrite-database#110]
Hi,

i am getting the bellow error, it looks like only android Oreo is supported. is there a way i can get it to work with older versions ?

MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)

**Comment by angelix** [comment]
Same here, problem occurs only if i change the nitrite version to 3.1.0, 3.0.2 compiles fine.
```
The app gradle file must have a dependency on com.google.firebase:firebase-core for Firebase services to work as intended. |  
Supported source version 'RELEASE_7' from annotation processor 'shortbread.ShortcutProcessor' less than -source '1.8' |  
com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/angelos/.../build/intermediates/transforms/androidGradleClassShrinker/development/debug/4 |  
com.android.builder.dexing.DexArchiveBuilderException: Error while dexing. |  
com.android.tools.r8.CompilationFailedException: Compilation failed to complete |  
com.android.tools.r8.utils.AbortException: Error: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26) |  
null |  
MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26) |  


```

**Comment by angelix** [comment]
@dustin-auby Do you use Firebase Performance Monitoring? If yes try disable them and try again.

**Comment by anidotnet** [comment]
@angelix did you able to find out what causing nitrite 3.1.0 to throw this error, where as nitrite 3.0.2 does not? Nitrite itself does not have any firebase dependencies.

**Comment by dustin-auby** [comment]
I don't have any Firebase dependencies in the project at the moment. Here is the full error that the build gives. i don't use H2 database so im not sure where that comes into play. as soon as i remove nitrite from the project the problem s gone.

```
MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26) 

com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\The-pc\.gradle\caches\modules-2\files-2.1\com.h2database\h2-mvstore\1.4.197\9ec0f6b8ea61709d47102e90d7349c0eeda1e030\h2-mvstore-1.4.197.jar |  
com.android.builder.dexing.DexArchiveBuilderException: Error while dexing. |  
com.android.tools.r8.CompilationFailedException: Compilation failed to complete |  
com.android.tools.r8.utils.AbortException |  
```

**Comment by angelix** [comment]
@dustin-auby try using nitrite 3.0.2 to see if the problem persists.
@anidotnet I used firebase performance monitor on my project, after removing it I was able to build the project with nitrite 3.1.0. So maybe there is a weird problem with D8? A combination of dependencies causing the problem?

**Comment by anidotnet** [comment]
Ahh! now I remember when you say issue with D8. There was indeed a problem with D8 with mvstore. As mvstore was built with java9 for module support, the recent version of gradle build tool is required to mitigate this issue.

Please look into the example project's build file - https://github.com/dizitart/nitrite-database/blob/master/example-android-app/build.gradle and you have to use gradle 4.9 at minimum.

**Comment by anidotnet** [comment]
@dustin-auby are you able to resolve this issue?

**Comment by dustin-auby** [comment]
It worked when using 3.0.2 still trying to get the latest version working, i see you are using an alpha version in your gradle file i would prefer not to do this `gradle:3.3.0-alpha04` will it still work with a stable version ?

**Comment by anidotnet** [comment]
Stable version has a bug in r8. The fix is only there in the alpha version. Here it is the r8 issue tracker - https://issuetracker.google.com/issues/77587908

If you don't want to use alpha version then stick to 3.0.2 now. Once there is a stable release of gradle plugin then you can update nitrite to 3.1.0 or later. But there is nothing from nitrite perspective I can do to mitigate this.
