### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by ArthurSav** [dizitart/nitrite-database#115]
Hi, is there a benchmark page?

I noticed slow performance when dealing with large lists.

i.e Inserting a list of 1000+ items will take at least **800-1400ms**. List contains very simple POJOs that implement **Mappable**.

I noticed the same performance when trying to **.remove()** a repository that contains many items.
i.e when performing **nitrite.getRepository(POJO.class).remove(ObjectFilters.ALL)** on a repository that contains 1000+ items it takes **800-1400ms**

What is the expected performance here?

One trick to increase performance is to wrap the list into a another POJO and insert the POJO. But then you can't query/search items directly.

p.s running **v3.0.2**, test was done with a galaxy s8

**Comment by anidotnet** [comment]
If you are using indexing it will take some extra times as the collection needs to be locked down while updating index entry to prevent data race. Text indexing takes a little more time.

Here is some benchmark for different condition:

```java
@Data
@Indices({
        @Index(value = "firstName", type = IndexType.NonUnique),
        @Index(value = "age", type = IndexType.NonUnique),
        @Index(value = "text", type = IndexType.Fulltext),
})
public static class PerfTest implements Mappable {
    private String firstName;
    private String lastName;
    private Integer age;
    private String text;

    @Override
    public Document write(NitriteMapper mapper) {
        Document document = new Document();
        document.put("firstName", firstName);
        document.put("lastName", lastName);
        document.put("age", age);
        document.put("text", text);
        return document;
    }

    @Override
    public void read(NitriteMapper mapper, Document document) {
        this.firstName = (String) document.get("firstName");
        this.lastName = (String) document.get("lastName");
        this.age = (Integer) document.get("age");
        this.text = (String) document.get("text");
    }
}

@Test
public void testRepoPerformanceWithoutIndex() {
    // warm-up
    List<PerfTest> items = getItems(PerfTest.class);
    ObjectRepository<PerfTest> repo = db.getRepository(PerfTest.class);
    for (PerfTest item : items) {
        assertNotNull(item);
        repo.insert(item);
    }
    repo.remove(ObjectFilters.ALL);
    repo.drop();

    // actual calculation
    repo = db.getRepository(PerfTest.class);
    long start = System.currentTimeMillis();
    for (PerfTest item : items) {
        repo.insert(item);
    }
    long diff = System.currentTimeMillis() - start;
    System.out.println("Time taken to insert 10000 indexed items - " + diff + "ms");

    start = System.currentTimeMillis();
    repo.remove(ObjectFilters.ALL);
    diff = System.currentTimeMillis() - start;
    System.out.println("Time taken to remove 10000 indexed items - " + diff + "ms");
}

private <T> List<T> getItems(Class<T> type) {
    PodamFactory generator = new PodamFactoryImpl();
    List<T> items = new ArrayList<>();
    for (int i = 0; i < 10000; i++) {
        items.add(generator.manufacturePojoWithFullData(type));
    }
    assertEquals(items.size(), 10000);
    return items;
}

```

Now the result:

Time taken to insert 10000 indexed items - 2076ms
Time taken to remove 10000 indexed items - 1879ms

Time taken to insert 10000 indexed items (w/o text index) - 790ms
Time taken to remove 10000 indexed items (w/o text index) - 934ms

Time taken to insert 10000 non-indexed items - 144ms
Time taken to remove 10000 non-indexed items - 127ms


Platform Details:

Nitrite Version = 3.1.0
OS: Ubuntu 18.04.1
Memory: 16 GiB
Processor: Intel® Core™ i7-3770 CPU @ 3.40GHz × 8 

-------

Now that being said, I am doing some refactoring of the code in version 4.0.0, where you could see improvements in various areas.

**Comment by ArthurSav** [comment]
No indexing, just **@Id**
Also worth mentioning that the same speeds would be x8 more on mobile.
