### ISSUE TITLE
Slow performance of find method on repository with large number of objects

### ISSUE THREAD

**Issue by AdamPayne** [dizitart/nitrite-database#119]
Having an ObjectRepository with 200 000 plus objects stored causes a significant slowdown when trying to find objects by a certain single criteria. Are there any suggestions on how to improve the performance?

**Comment by anidotnet** [comment]
Create indices based on your criteria for faster access. Here is the documentation - https://www.dizitart.org/nitrite-database/#indexing

**Comment by anidotnet** [comment]
@AdamPayne did adding indexing helps? If you have got desired result, let me know so that I can close this issue.

**Comment by AdamPayne** [comment]
Yes, it helped. Thank you! Feel free to close the issue.
