### ISSUE TITLE
getIdField(NitriteMapper, Class<T>) does not account for Jackson

### ISSUE THREAD

**Issue by ZiluckMichael** [dizitart/nitrite-database#120]
Right now the method `ObjectUtils.getIdField(NitriteMapper, Class<T>` only accounts for Nitrite's internal annotation system. Most of the time, this would be fine. However, there are some users who like being able to have classes be multi-purpose. 

In a situation where one uses `@JsonTypeId`, names the field "id", or uses another API that uses Jackson (like Jongo's `@MongoId`), they would have to reimplement the content to make it compatible with Nitrite.

It would be really nice if the NitriteMapper had another method that checks if the field is the ID field. Something along the lines of `NitriteMapper.isFieldId(Field) ` would make using your system even better than it already is.

Thanks much! Your system is fantastic so far 👍

**Comment by anidotnet** [comment]
Thank you for your kind words. :smiley: 

What I understood, you want to reuse a class in nitrite which is meant for other purpose say jongo, but I don't understand what is keeping you to add another annotation `org.dizitart.no2.objects.Id` to the id field? Moreover, there are other annotations also for indexing and all, so what would be the strategy for them?

And IMO, multipurpose class is a bad design choice. It would always be better to keep domain classes separate. It keeps your code clean and maintainable.
