### ISSUE TITLE
Very slow deletion of Objects in large quantities

### ISSUE THREAD

**Issue by AdamPayne** [dizitart/nitrite-database#121]
We have a repository of 200 000 objects and deletion of all of them is really slow due to reindexing. Is there any way to delete all of them at once and then start the reindexing?

**Comment by anidotnet** [comment]
If you want to delete the repository content, use

```java
repository.remove(ObjectFilters.ALL);
```

or to drop the repository all together use

```java
repository.drop();
```

Both of these operations deletes the index entries as well.

If you want to delete all indexes only, use

```java
repository.dropAllIndices();
```

or to drop a specific index for a field use

```java
repository.dropIndex("fieldName");
```

All of these are in the documentation. I'll strongly suggest to go through it. Your journey will be real smooth.
