### ISSUE TITLE
id and _id confusion

### ISSUE THREAD

**Issue by ShlomiRex** [dizitart/nitrite-database#125]
I got a class: Trivia
In it I must have @Id String id; member. (If not, I get errors)
Why should I initialize id if the DB already does that??
I don't understand the porpuse of 
`public void read(NitriteMapper mapper, org.dizitart.no2.Document document) `
and
`public org.dizitart.no2.Document write(NitriteMapper mapper) `
and I also don't understand ObjectFilters. Is this mechanicsem checks the nitrite collection itself? or the actual object id?

How do I find an object in ObjectRepository with the Database id itself?
Or better, how to find object by given object?

![screenshot from 2018-12-25 13-43-05](https://user-images.githubusercontent.com/17744127/50421722-3702a380-084b-11e9-8bbb-e71446dd308a.png)

![screenshot from 2018-12-25 13-46-21](https://user-images.githubusercontent.com/17744127/50421755-7fba5c80-084b-11e9-8a34-e6f33a0046e9.png)

Note:
I got a file with jsons in it.
In order not to have String id = null, I declare dummy id in the jsons.
I read the json file, read json object, and convert it to Trivia object, and put the object inside the DB.

Inside Trivia class:
My functions:```

    @Override
    public org.dizitart.no2.Document write(NitriteMapper mapper) {
        org.dizitart.no2.Document nitd = new org.dizitart.no2.Document();
        nitd.put("id", id);
``````

@Override
    public void read(NitriteMapper mapper, org.dizitart.no2.Document document) {
        initFromDocument(document);
    }

    public void initFromDocument(org.dizitart.no2.Document document) {

        this.id = document.get("_id").toString();
```

**Comment by anidotnet** [comment]
> Why should I initialize id if the DB already does that??

`@Id` annotation is needed to identify the object inside an `ObjectRepository` uniquely. It creates a default index entry on the id field for faster search. Nitrite does not store the object directly. It converts the object into a `Document` and store it.

`_id` field identifies a document inside the db. It is not directly tied up with `@Id` field of an object. The type of `_id` field is always `NitriteId`. So for an object in an `ObjectRepository` if you want to set a custom field of arbitrary data type as an id field you need an annotation to mark the field. That is why we have `@Id` annotation.

More on this in documentation: https://www.dizitart.org/nitrite-database/#insert

> I don't understand the porpuse of
`public void read(NitriteMapper mapper, org.dizitart.no2.Document document)` 
and
`public org.dizitart.no2.Document write(NitriteMapper mapper)`

It converts an object to a Document with out using reflection. Here is the detailed documentation: https://www.dizitart.org/nitrite-database/#mappable

> How do I find an object in ObjectRepository with the Database id itself?
Or better, how to find object by given object?

`T getById(NitriteId nitriteId);`

Here is the documentation: https://www.dizitart.org/nitrite-database/#find

**Comment by ShlomiRex** [comment]
> > Why should I initialize id if the DB already does that??
> 
> `@Id` annotation is needed to identify the object inside an `ObjectRepository` uniquely. It creates a default index entry on the id field for faster search. Nitrite does not store the object directly. It converts the object into a `Document` and store it.
> 
> `_id` field identifies a document inside the db. It is not directly tied up with `@Id` field of an object. The type of `_id` field is always `NitriteId`. So for an object in an `ObjectRepository` if you want to set a custom field of arbitrary data type as an id field you need an annotation to mark the field. That is why we have `@Id` annotation.
> 
> More on this in documentation: https://www.dizitart.org/nitrite-database/#insert
> 
> > I don't understand the porpuse of
> > `public void read(NitriteMapper mapper, org.dizitart.no2.Document document)`
> > and
> > `public org.dizitart.no2.Document write(NitriteMapper mapper)`
> 
> It converts an object to a Document with out using reflection. Here is the detailed documentation: https://www.dizitart.org/nitrite-database/#mappable
> 
> > How do I find an object in ObjectRepository with the Database id itself?
> > Or better, how to find object by given object?
> 
> `T getById(NitriteId nitriteId);`
> 
> Here is the documentation: https://www.dizitart.org/nitrite-database/#find

Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
When:
```
        ObjectRepository<Trivia> repo = db.getRepository(Trivia.class);
        NitriteId id2 = NitriteId.createId(Long.valueOf(id));
        return repo.getById(id2);
```

**Comment by anidotnet** [comment]
I guess you are missing the point again.

```
NitriteId id2 = NitriteId.createId(Long.valueOf(id));
```

What is the value of variable `id`? It should be auto-generated by the db only. You cannot use your own value while creating `NitriteId`. As I mentioned earlier, `NitriteId` and `@Id` field are different. The former one is the value of `_id` field in the underlying document, where as later is your custom field. 

The `T getById(NitriteId nitriteId);` can be used if you have `NitriteId` from the db. Like the `WriteResult` you get after inserting one object.

Here is the example:

```java

public class Trivia {
	@Id public String myName;
	...
}

ObjectRepository<Trivia> repo = db.getRepository(Trivia.class);
Trivia item = new Trivia();
item.myName = "Some Random Name";
WriteResult result = repo.insert(item);

// get the actual nitrite id generated in db
NitriteId nitriteId = Iterables.firstOrDefault(result);

Trivia byId = repo.getById(nitriteId);
```

Or you can get the `NitriteId` directly from the object.

Example:

```java
public class Trivia {
	@Id public NitriteId dbId;
	public String myName;
	...
}

ObjectRepository<Trivia> repo = db.getRepository(Trivia.class);
Trivia item = new Trivia();
// do not set the dbId field, nitrite will set it for you with auto generated NitriteId.
item.myName = "Some Random Name";
WriteResult result = repo.insert(item);

Cursor<Trivia> cursor = repo.find();
for(Trivia trivia: cursor) {
	System.out.println(trivia.dbId); // prints the db generated value
    
	Trivia trivia2 = repo.getById(trivia.dbId);
	assertEquals(trivia, trivia2); // holds true
}
```
