### ISSUE TITLE
Supporting multiple indices in a single query

### ISSUE THREAD

**Issue by sheinbergon** [dizitart/nitrite-database#132]
It's clearly stated compound indices are not supported.
However, does a query processes multiple indices (assuming those are defined) for multiple fields, when the query parameters contain multiple fields?

**Comment by anidotnet** [comment]
If you create indexes on multiple fields, then you can leverage them by using filters like - `and()`, `or()`.

Example here - https://github.com/dizitart/nitrite-database/blob/master/nitrite/src/test/java/org/dizitart/no2/CollectionFindByIndexTest.java#L107

You can use non-indexed field also in the query.
