### ISSUE TITLE
Error when using ObjectFilters.ALL with an empty ObjectRepository

### ISSUE THREAD

**Issue by ariel-lenis** [dizitart/nitrite-database#14]
Hi, i'm creating an empty database and after that trying to get the count of the elements for an objectRepository (at begin i expect a 0) returns this exception:

I'm using something like this:
`int count = objectRepository.find(ObjectFilters.ALL).totalCount()`

And this is a part of the exception:

```
 org.dizitart.no2.exceptions.ValidationException: NO2.1076: filter can not be null
                                                                                    at org.dizitart.no2.util.ValidationUtils.notNull(ValidationUtils.java:76)
                                                                                    at org.dizitart.no2.objects.DefaultObjectRepository.find(DefaultObjectRepository.java:188)
```

**Comment by ariel-lenis** [comment]
As a workaround, a negation of an impossible case is useful:

`ObjectFilter targetFilter = ObjectFilters.not(ObjectFilters.eq("_id", ""))`

**Comment by anidotnet** [comment]
Instead of using ```objectRepository.find(ObjectFilters.ALL)```, you should use ```objectRepository.find()``` if you want to select all elements.

But the error you are getting it is a miss from my end. In the next release, I'll provide a fix.

**Comment by ariel-lenis** [comment]
Then objectRepository.find(ObjectFilters.ALL) must work in a future release?

Thanks for your help!!!

**Comment by anidotnet** [comment]
Yes it would.

**Comment by anidotnet** [comment]
Fix is currently in the master. Will be released soon.
