### ISSUE TITLE
eq operator on string field is not working

### ISSUE THREAD

**Issue by adhamelia** [dizitart/nitrite-database#142]
@anidotnet 

Do I  have to create index on string fields for searching purpose ??? eq operator is not working even after creating index on the field.

        try
        {
            Nitrite db = Nitrite.builder().filePath("D:\\demo.db").openOrCreate();

           Document doc = new Document();

            doc.put("user.name","u31").put("user.password","aaa31").put("age",31);

            db.getCollection("users").insert(doc);

            doc = new Document();

            doc.put("user.name","u32").put("user.password","aaa32").put("age",32);

            db.getCollection("users").insert(doc);

            doc = new Document();

            doc.put("user.name","u33").put("user.password","aaa33").put("age",33);

            db.getCollection("users").insert(doc);

            doc = new Document();

            doc.put("user.name","u34").put("user.password","aaa34").put("age",34);

            db.getCollection("users").insert(doc);

            db.getCollection("users").createIndex("user.name", indexOptions(IndexType.NonUnique));

            db.getCollection("users").createIndex("user.password", indexOptions(IndexType.NonUnique));

            db.commit();

         System.out.println(db.getCollection("users").find(eq("user.name","u31")).toList());

        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }

**Comment by adhamelia** [comment]
Got the issue.. if field contains "." then it does not work. any work around of this ??? We have to use "." in the field name it self.

**Comment by anidotnet** [comment]
No way around till now. May be I can put some options to customize the field separator to the next major release 4.x.

**Comment by anidotnet** [comment]
Added the functionality in 4.x branch. But unfortunately could not accommodate in 3.x branch.

**Comment by adhamelia** [comment]
When 4.x will be released ??? Or do i have to manually merge the changes ???

**Comment by anidotnet** [comment]
I don't have any release date planned for 4.x. But I'll see if I can merge this changes to 3.3.0.

**Comment by adhamelia** [comment]
@anidotnet  can you please help to merge this feature in 3.3.0 ??? it's very crucial for us to use . dot notation.... I can do it if you guide me.

**Comment by anidotnet** [comment]
You can check the commit log attached to this issue and make changes in your fork as per your convenience.
