### ISSUE TITLE
ObjectFilters.text() not working with uppercase letters

### ISSUE THREAD

**Issue by mregnauld** [dizitart/nitrite-database#143]
Hello,

When I use `ObjectFilters.text()` to find objects in my database, it works fine as long as the data don't use uppercase letters. If there are uppercase letters, it looks like they are ignored.

For example, when I execute `ObjectFilters.text("myField", "*demo*")` and the field `myField` of one of the objects has "demo test" in it, it works.
But, when I execute `ObjectFilters.text("myField", "*Demo*")` and the field `myField` of one of the objects has "Demo test" in it, the object is ignored.

Thanks for your help.

**Comment by anidotnet** [comment]
Which version of nitrite are you currently on?

With latest 3.2.0, I can't reproduce this.

```java
@Data
@Indices({
        @Index(value = "name", type = IndexType.Fulltext)
})
public class PersonEntity {
    @Id
    private String uuid;
    private String name;

    public PersonEntity() {
        this.uuid = UUID.randomUUID().toString();
    }

    public PersonEntity(String name) {
        this.uuid = UUID.randomUUID().toString();
        this.name = name;
    }
}


@Test
public void testIssue143() {
    PersonEntity p1 = new PersonEntity("Demo test");
    ObjectRepository<PersonEntity> repository = db.getRepository(PersonEntity.class);
    repository.insert(p1);

    ObjectFilter filter = text("name", "*Demo*");
    assertEquals(repository.find(filter).size(), 1);
}
```

**Comment by mregnauld** [comment]
I'm currently on 3.2.0

**Comment by mregnauld** [comment]
I finally managed to reproduce the problem by changing the index type:

```
@Indices({
        @Index(value = "name", type = IndexType.NonUnique)
})
```

If I use the `IndexType.Fulltext` type, it works every time.
But if I use the `IndexType.Fulltext` type, it only works with lowercase letters.

I don't know if it's a bug or not, but it's for your information.

**Comment by anidotnet** [comment]
> But if I use the IndexType.Fulltext type, it only works with lowercase letters.

Did you mean `IndexType.NonUnique` or `IndexType.Fulltext`?

**Comment by mregnauld** [comment]
Oh my bad, I mean: But if I use the `IndexType.NonUnique` type, it only works with lowercase letters.

**Comment by anidotnet** [comment]
Are you using `text()` filter with `IndexType.NonUnique`? `text()` filter can only be used with `IndexType.Fulltext` indexed field. You can not use wild card also for `IndexType.NonUnique`.

It would be better if you can provide a reproducible code, so that I can look into it properly.

**Comment by mregnauld** [comment]
OK, good to know, thanks.

You can easily reproduce the problem by just changing the index type as follow:
```
@Indices({
        @Index(value = "name", type = IndexType.NonUnique)
})
```

**Comment by anidotnet** [comment]
Yeah. Then you can't use `text()`. You have to use `eq()` or `regex()` filter for that.

**Comment by mregnauld** [comment]
OK, thanks for the info!
