### ISSUE TITLE
Sorting with accents

### ISSUE THREAD

**Issue by mregnauld** [dizitart/nitrite-database#144]
When I use `FindOptions.sort("myField", SortOrder.Ascending)`, I got the results with the correct sorting, for example: Apple, Orange, Pineapple.

But when I do the same with an accent in `myField` (for example: Ôrange), I got the following result: Apple, Pineapple, Ôrange, while I would expect: Apple, Ôrange, Pineapple.

It doesn't look like it's technically a bug, but it could be a nice improvement, especially for non english users.

**Comment by anidotnet** [comment]
You can test now in latest snap shot version - 3.3.0-SNAPSHOT

**Comment by mregnauld** [comment]
I'll do that. Thanks!
