### ISSUE TITLE
Are CRUD operations atomic?

### ISSUE THREAD

**Issue by shasait** [dizitart/nitrite-database#145]
Hi - in the docs you stat:
>  It does not support sharding and ACID transaction

But I cannot find if CRUD operations are atomic = the change is visible for other threads after fully complete = if I update two document properties others see either none changed or both changed, but never only one changed.

Additionally it would be nice to know if it is thread safe.

**Comment by anidotnet** [comment]
As nitrite does not support ACID transaction, a partial, or ongoing updates can be visible by other threads. So in other words it is not atomic. If you are updating two document properties, one has changed and you are in the middle of updating other, another thread will see only one changed. This is a nature of a typical nosql database.

And all collection and object repositories are thread-safe and suitable for concurrent usage.
