### ISSUE TITLE
Wondering about performance in comparison to other embedded database such as Sqlite, Derby, H2

### ISSUE THREAD

**Issue by bigbang489** [dizitart/nitrite-database#146]
I'm planning a small business web project which may serve 50 concurrent users.
After few days searching for a embedded DB, NO2 looks very promising, but I have a concern about performance.
Have you compared CRUD to other embedded DB such as Sqlite, Derby, H2?
Is NO2 suitable for large data, example 10M documents?
Thank you for spending time on my question.

**Comment by anidotnet** [comment]
Recently, I have provided some performance fix for #133 in 3.2.0 release. Results (numbers are _**microseconds per operation (us/op)**_ ) - 

 | Number of entities | Also read data? | Indexed field disperssion |Iterations | Results|
 |--------------------------|-----------------------|----------------------------------|-------------|----------|
 |        100000           | true                     | 5000   | 12   | 44.578|
 | 100000                  | true                   | 10000   | 12   |27.146|
| 100000         |true     |              20000   | 12  |18.983 |
| 100000       | false    |                5000   | 12   |   3.660 |
| 100000       | false    |               10000  | 12   |   3.732 |  
| 100000       | false   |                20000  | 12   |   3.838 |
| 200000       | true    |                5000    | 12  | 97.593 |
|         200000 |        true |                  10000 |   12  | 58.124 |
|         200000 |        true  |                 20000 |  12  | 28.737 |
|         200000 |       false  |                  5000  |  12  |    4.094  |
|         200000 |       false  |                 10000 |  12  |    3.966  |
|         200000 |       false  |                 20000 |  12 |     3.849  |

 The benchmark code is there in the issue description. See if this fits your bill.

**Comment by sheinbergon** [comment]
I've recently lectured about Nitrite in the context of Kotlin embedded databases.

https://www.slideshare.net/IdanShinberg/nitrite-choosing-the-rite-embedded-database

Slides 28-31 contain benchmark comparisons to SQLite, as well as links to the actual benchmark code

**Comment by anidotnet** [comment]
@sheinbergon I highly appreciate it. It is a nice, informative and deeply thought out presentation. Thank you very much for spreading the words. Just curious how was the overall response there?

**Comment by sheinbergon** [comment]
@anidotnet It went pretty well, I think. People weren't really all that aware on the subject of embedded database in general, so it also served as a good entry point. 

Would you mind linking to that presentation from the front /mainpage of the github project and maybe also the documentation site?  I think It'd would greatly help new-comers evaluate your project in terms of features, maturity, performance, tweaks and so forth

**Comment by anidotnet** [comment]
@sheinbergon I have updated the readme section with the details.
