### ISSUE TITLE
Could not find or load main class org.dizitart.no2.ui.NitriteManager

### ISSUE THREAD

**Issue by Vijeta141** [dizitart/nitrite-database#148]
When i try to use java -jar nitrite-explorer-3.2.0.jar it gives the error - 
`Could not find or load main class org.dizitart.no2.ui.NitriteManager`.
The file NitriteManager.class does exist and can be seen when the jar is extracted.
I am not being able to run nitrite-explorer.

**Comment by anidotnet** [comment]
What version of java are you on? Make sure you have javafx installed. If you are on oracle jdk 8+ it would run fine. If you are on openjdk 8+, make sure you have openjfx installed.

For me it is running just fine.

![image](https://user-images.githubusercontent.com/696662/55646466-e828ba80-57f8-11e9-9061-3aba032618e4.png)
