### ISSUE TITLE
Nitrite in web app with 100 databases

### ISSUE THREAD

**Issue by bigbang489** [dizitart/nitrite-database#149]
My app has 100 users (tenants), each tenant has their own db, I considering using no2. But I have some questions:
- does it create any background thread in my app?
- as I read in the reference, there will be a replication thread to do the synchronization job, the question is: if my 100 DBs synchronize data, it will create 100 replication threads or only one dedicated sync thread is created for all databases?
- if I keep 100 databases open, do you think that is a good practice? If nitrite create threads for each db, then there will be hundred threads, a poor design.
Thanks

**Comment by anidotnet** [comment]
Yes it will create at least 100 threads for replication. The ideal design for you would be to use one db and create separate ObjectRepository/NitriteCollection for each user.

Example:

```java

// For NitriteCollection
db.getCollection("book" + "user1");
db.getCollection("book" + "user2");

// For ObjectRepository
db.getRepository("user1", Book.class);
db.getRepository("user2", Book.class);
```

Having many collections in one database does not affect the performance of accessing one collection.

If you have any such questions in future, please post it to our gitter chat room.

**Comment by bigbang489** [comment]
Thank you so much
