### ISSUE TITLE
Documents inserted with ObjectRepository are not visible for Nitrite instance

### ISSUE THREAD

**Issue by voplex95** [dizitart/nitrite-database#152]
In my project I have created an `ObjectRepository` for my domain object.

When I insert a new document using this repository:
`objectRepository.insert(obj);`

And then try to get it back:
`objectRepository.find(eq(ID_FIELD, id)).firstOrDefault()`

It works as expected. But when I try to use `Nitrite` instance from which `ObjectRepository` was created and call:
`nitrite.listCollectionNames();`

It returns an empty list. Please, advice.

**Comment by anidotnet** [comment]
Please call `nitrite.listRepositories()` to get the set of all fully qualified class names corresponding to all `ObjectRepository`s in the store.

**Comment by voplex95** [comment]
@anidotnet So I can not use `db.getCollection(name).find(eq("id", id)).firstOrDefault()` and have to use  `ObjectRepository` all the time? I thought `ObjectRepository` is just a convenient wrapper and nothing more, but it looks like collection and repository are completely different concepts that can not be used together.

**Comment by anidotnet** [comment]
`ObjectRepository` contains managed objects and `NitriteCollection` contains documents. Though `ObjectRepository` is implemented using `NitriteCollection`, calling `nitrite.listCollectionNames()` does not give you underlying `NitriteCollection` of defined `ObjectRepository`. **This rule is enforced to prevent corruption of object data**.

`nitrite.listCollectionNames()` gives you user defined `NitriteCollection`s, where as `nitrite.listRepositories()` gives you user defined `ObjectRepository`s. I hope it is clear now.
