### ISSUE TITLE
Errors connecting to database inside a Play Framework controller

### ISSUE THREAD

**Issue by mnmami** [dizitart/nitrite-database#153]
Hello,
I'm trying to run the following basic code from within a Play Framework controller:
```scala
import org.dizitart.no2.Nitrite
import org.dizitart.no2.Document

class DatabaseController @Inject()(cc: ControllerComponents, playconfiguration: Configuration) extends AbstractController(cc) {

def db = Action {
  val DBfile = "/path/to/DBfile"
  var db = Nitrite.builder()
	.filePath(DBfile)
	.openOrCreate()

  var collection = db.getCollection("collection")
  var doc = Document.createDocument("aa", "aa")
	.put("bb", "bb")

  collection.insert(doc)
  //db.close()

  Ok(views.html.squerall("db", null))
  }
}
```

If I request the controller (opening the web page) once, the DB file gets created, but when I refresh, I get the following error:
```
[NitriteIOException: NO2.2001: database is already opened in other process]
```
If I start again (delete fileDB), uncomment `db.close()` and refresh, the DBfile gets created but I get the following error:
```
[RuntimeException: java.lang.NoSuchMethodError: org.h2.mvstore.MVStore.compactMoveChunks()V]
```
then if I refresh the second time I get the first error (database already opened) again.

Note that the same code without `db.close()` works in a normal Scala app.

**Comment by anidotnet** [comment]
I can't help you much with scala/play, as I don't know it at all. But what you are facing is common mistakes. Thumb rule is you can open a db file once. Unless you close it you can't open it again from the same process or any other process. So you need to place your db opening logic in a singleton component and inject in your controller. Put a check, if db is not closed, don't call the action to open it again, reuse the already opened instance.

Use `ApplicationLifecycle.addStopHook()` only to close the database. This will ensure, the db will be closed only when your application shuts down.
