### ISSUE TITLE
Need some sort of group by functionality

### ISSUE THREAD

**Issue by dustin-auby** [dizitart/nitrite-database#154]
Basically i want to select all from a repository that potentially has duplicates, but i only want to select one of each type ignoring duplicates like mysql group by does

**Comment by anidotnet** [comment]
Java 8 stream api is your best bet here. Call `toList()` from the returned cursor and use `Collectors.groupingBy` api to group your result.

I deliberately left out these kind of functions as the db processing is happening inside the same jvm process. It would be better to let the developer implement them using api of his own choice.

**Comment by letuananh035** [comment]
But Collectors.groupingBy and any function from .stream() support only >= API 24

**Comment by anidotnet** [comment]
@letuananh035 you can use stream backport - https://github.com/streamsupport/streamsupport
