### ISSUE TITLE
Filter for Dates

### ISSUE THREAD

**Issue by a13u** [dizitart/nitrite-database#155]
Hi!
I use Nitrite via Maven:

```
	<dependency>
 	   <groupId>org.dizitart</groupId>
 	   <artifactId>nitrite</artifactId>
  	  <version>3.1.0</version>
	</dependency>
```

My Bean Class looks like the following (date is java.util.date):

```
@Indices({ @Index(value = "id", type = IndexType.Unique) })
@JsonIgnoreProperties(ignoreUnknown = true)
public class A extends Storeable implements Comparable<A>{
	@Id
	public String id; //carrier id 


	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXX")
	public Date updateTime=new Date();
	
	public void setCurrentTime() {
		updateTime=new Date();
	}
	
	@Override
	public String getId() {
		return id;
	}
```

I tried to implement a filter for the date. So I tried the following:
```
Date availableDate=new Date(System.currentTimeMillis() - 3600 * 1000);
Cursor<A> cursor=repo.find(gt("updateTime", availableDate));
```

Here I Get an Exception: 
```
Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
	at java.lang.String.compareTo(String.java:111)
	at org.dizitart.no2.filters.GreaterThanFilter.matchedSet(GreaterThanFilter.java:81)
	at org.dizitart.no2.filters.GreaterThanFilter.apply(GreaterThanFilter.java:64)
	at org.dizitart.no2.objects.filters.GreaterObjectFilter.apply(GreaterObjectFilter.java:59)
	at org.dizitart.no2.internals.SearchService.find(SearchService.java:66)
```

What is the easiest to do such a comparison?

**Comment by anidotnet** [comment]
Problem is with this annotation `@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXX")` on your date field. Nitrite handles all date as long value even during comparison. 

But here you are explicitly telling jackson to store date as string (remember, nitrite uses jackson to store an object as a document). You are passing a date object for comparison, which nitrite is converting into long before comparison.

So to get the desired result, remove the `@JsonFormat` annotation, and it will work just fine.
