### ISSUE TITLE
Nitrite Explorer gives ClassNotFoundException: scala.collection.mutable.HashMap

### ISSUE THREAD

**Issue by mnmami** [dizitart/nitrite-database#156]
Hi,
When I try on Nitrite Explorer to open a collection storing a document whose value is `scala.collection.mutable.Map` I get:
```
java.lang.ClassNotFoundException: scala.collection.mutable.HashMap
```
I can see that the document has been indeed added by running `find` on the collection.

To reproduce this, simply create a new collection and insert a document with the value being a `mutable.HashMap` object. This is what I use to reproduce it:
```scala
var db = Nitrite.builder()
      .compressed()
      .filePath("pathToDB")
      .openOrCreate()

    var properties : scala.collection.mutable.Map[String,String] = scala.collection.mutable.Map()

    properties += ("aaa" -> "111")
    properties += ("bbb" -> "222")

    var collection = db. getCollection("collection")
    var doc = Document.createDocument("ccc", "333")
      .put("ddd", "444")
      .put("properties", properties)

    collection.insert(doc)
```

**Comment by anidotnet** [comment]
Of course it will fail. Nitrite explorer is a java program, it does not have scala classes in its classpath. You need to add scala libraries in the classpath to make it work, or use java.util.Map instead.
