### ISSUE TITLE
Is possible to exclude fields in POJOs for ObjectRepository?

### ISSUE THREAD

**Issue by ariel-lenis** [dizitart/nitrite-database#16]
Hi, currently i'm using the ObjectRepository to store my objects, but there is an annotation to exclude specific fields to be stored? 
For instance this is my class:
```
class MyInformation {
       @Id
       String myId;
       String valueA;
       String valueB;
}
```

I want to exclude the valueB field to be stored and use it just in run time (because it changes dynamically at run time).

**Comment by anidotnet** [comment]
Nitrite uses Jackson. So either you use the annotation ```@JsonIgnore``` or you use the keyword ```transient```

```java
class MyInfo {
       transient String valueB;
}
```
or

```java
class MyInfo {
       @JsonIgnore String valueB;
}
```

**Comment by ariel-lenis** [comment]
Great, thanks!
It will be helpfully to document that.

**Comment by anidotnet** [comment]
ok
