### ISSUE TITLE
Recursive Indexing

### ISSUE THREAD

**Issue by TareqK** [dizitart/nitrite-database#161]
Is there a way to recursively index all text fields in a document? ie, if have a field whose value is a document, is there a way to index that document recursively. Also, is it possible to recursively query things?

**Comment by anidotnet** [comment]
I don't get you. Are you talking about indexing by embedded field? Can you please provide some pseudo code of what you are trying to achieve?

**Comment by TareqK** [comment]
yes, essentially, i am getting a document whose structure i am not sure about, and would like to index the whole JSON object, including sub objects.

**Comment by anidotnet** [comment]
Currently nitrite does not support multikey, compound indexing. So indexing dynamic fields will not be very performant. One thing you can do is to iterate the json object, access the fields, check if indexing exists for that field, if not create an index.

But again while utilizing this index, when you query the collection, how are you suppose to provide the field name if you don't know it beforehand?

**Comment by TareqK** [comment]
The general idea is to host nitrite "sort of" like a mongodb server, for testing something out(i am basically trying out nitrite in every possible way its  possible and not possible to use) . So the client(in this case another app) knows what it wants, but nitrite does not know

**Comment by anidotnet** [comment]
Though nitrite follows some mongodb syntax, but it can not replace mongo, it is not built to serve that purpose. Though I have plans to introduce some advanced features like spatial index, compound indexing in next major release, but being a powerful embedded database is its main goal, not to replace a sever side database like mongo.
