### ISSUE TITLE
Find Error When doing embedded object queries

### ISSUE THREAD

**Issue by TareqK** [dizitart/nitrite-database#162]
So im trying to do an embedded object query, and there seems to be a weird issue. I tried debugging the code, and for some reason, instead of seeing the returned embedded document as a document, it is seeing it as a LinkedHashMap and therefore not searching inside it. 
![linkedHashMapNotDocument](https://user-images.githubusercontent.com/18736962/57216643-19172d80-6ff9-11e9-8b32-7f202a28cbbf.png) ive attached  this screenshot here that shows exactly where this is happening. Wouldnt it make more sense to treat all Maps as documents as well? and if so, should i throw up a PR with this?

**Comment by anidotnet** [comment]
Can u provide me with a reproducible code? And let me know the version number of nitrite you are using.

**Comment by TareqK** [comment]
https://github.com/TareqK/nitrite-db-test

ive created this sample project, with a few unit tests, that tries to query docs and POJOs for embedded values. Strangely, all the queries on POJOs worked, but all the queries on the docs failed.

**Comment by TareqK** [comment]
Also im using nitrite 3.2.0

**Comment by TareqK** [comment]
![linkedHashMapNotDocumentObject](https://user-images.githubusercontent.com/18736962/57283467-dec09580-70b7-11e9-8e0f-64816ce41e9b.png)

It seems to work fine on on objects.

**Comment by TareqK** [comment]
![LinkedHashMapNotDocument2](https://user-images.githubusercontent.com/18736962/57284149-44f9e800-70b9-11e9-8af4-f453c3a75756.png)
More debug output, that shows that documents inside documents are being viewed as a linkedHashMap. Could this be a jackson issue?

**Comment by anidotnet** [comment]
The issue is with jackson. When you post a `Document` to your server, the jackson converts the embedded documents into a `LinkedHashMap`, hence is the issue.

The possible solution would be to create a new jackson module for `Document` which will properly parse the json and create embedded document properly. You can check the logic of [JacksonFacade](https://github.com/dizitart/nitrite-database/blob/master/nitrite/src/main/java/org/dizitart/no2/mapper/JacksonFacade.java) and similarly create your custom deserializer for document.

**Comment by TareqK** [comment]
Note that this issue is also happening when persisting documents in code
(not from http requests only). Still, in all cases a deserializer would
probably fix it

**Comment by anidotnet** [comment]
This will happen only in server context, when you have to reconstruct a document from json. You need that custom jackson module to make it work everywhere in server context.

**Comment by anidotnet** [comment]
Without the server context it works as expected.

```java
@Test
    public void testEmebeddedDocument() {
        Nitrite db = Nitrite.builder().filePath("/tmp/nitrite-test.db").openOrCreate();
        Document doc = new Document()
                .put("test", "something")
                .put("embed", new Document()
                        .put("firstEmbed", 123)
                        .put("secondEmbed", "test"));
        NitriteCollection collection = db.getCollection("test");
        collection.insert(doc);

        List<Document> documents = collection.find(Filters.eq("embed.firstEmbed", 123)).toList();
        assertEquals(documents.size(), 1);
    }
```
