### ISSUE TITLE
Allow to access collection of IDs from find result

### ISSUE THREAD

**Issue by tkainrad** [dizitart/nitrite-database#165]
I have recently started to use Nitrite as backend storage for large element collections displayed in a Java desktop application. I am very impressed with its performance.

However, I have an idea that could improve the speed further. Often, I require to get a list of IDs of all elements that fit a specific filter. At the moment I do the following:
```java
Cursor find = nitriteDatabase.getCollection(ELEMENT_COLLECTION)
    .find(Filters.eq(attributeName,
       value));

for (Document document : find)
{
    set.add(document.getId().getIdValue());
}
```
For indexed attributes, iterating through the `Cursor` object actually takes more time than the `find` operation itself. This is a little frustrating since the Cursor already has internally exactly what I need, the `Collection<NitriteId> resultSet`. 

I would suggest to allow access to the `resultSet` or add a way of retrieving the IDs without having to create the actual documents with all their key-value pairs.

Thank you for considering my request. If you point me to a solution you would be fine with, I could also think about contributing a PR myself.

**Comment by gibis07** [comment]
Did you already find a solution for this? We would need that, too!

**Comment by TareqK** [comment]
Me too! Ive been toying with it for webapps (testing scalable multi tenancy
arch), and this(in addition to the ability to throw an exception if
update/deletes don't change anything) are few of the things that are a bit
not-nice with nitrite


As a side note, does anybody else feel like we are all using nitrite in all
the places it was **not** designed to be used in?

**Comment by anidotnet** [comment]
Sorry guys, I am currently crammed up with my office work. Once I get some free time I'll work on it and hopefully introduce in 3.3.0.

**Comment by anidotnet** [comment]
> and this(in addition to the ability to throw an exception if
update/deletes don't change anything)

You should not do this, as this scenario is not exceptional. It's a very valid scenario. On the other hand `WriteResult` returns the number of effected elements. You should check it after modification and execute your logic based on the number.

**Comment by anidotnet** [comment]
This feature should be available in 3.3.0-SNAPSHOT now.

**Comment by tkainrad** [comment]
Wow, that was fast, thanks a lot!

**Comment by tkainrad** [comment]
Maybe a naive question, but is 3.3.0-SNAPSHOT published somewhere? It does not seem to be available through maven. We can wait for the full release, no problem, just wondering. Thanks again!

**Comment by anidotnet** [comment]
You can get it from maven snapshot repository. https://oss.sonatype.org/content/repositories/snapshots/org/dizitart/nitrite

**Comment by tkainrad** [comment]
Thanks, was not aware of this. Works like a charm!

**Comment by anidotnet** [comment]
Great. Glad to be of help.. 😀

**Comment by gibis07** [comment]
Thank you very much!
