### ISSUE TITLE
Can the id strategy in Nitrite be changed to be same or similar to MongoDB?

### ISSUE THREAD

**Issue by rwsbillyang** [dizitart/nitrite-database#169]
strategy in pseudocode:
```
if(_id field exists in object)  
{
      use the customized _id from app
}else
{
   use the default _id in Nitrite, eg NitriteId
}
```
Moreover, it seems @Id can only annotate long or NitriteId,  how about extending to annotate a field with any type, at least to support String? 

_id support for any type and @Id annotating any type are more convenient for development.

**Comment by anidotnet** [comment]
> Moreover, it seems @id can only annotate long or NitriteId, how about extending to annotate a field with any type, at least to support String?

Why do you say that? You can set a string field with `@Id`. Even you can mark any field `@Id` whose datatype implements `Comparable` and have a registered jackson module which can marshal that object into a value like `UUID`, `java.util.Date`, `java.time.LocalDateTime` (when `JavaTimeModule` is registered). As nitrite does not support composite key, you can not use custom object as an id, you have to implement a module which you can use to convert your custom type to a value (e.g. `NitriteIdModule`).

I have consciously avoided allowing `_id` to have any type. Think of it as a rowkey of a rdbms. It is immutable, this makes the internal logic like querying, indexing very simple and straight forward without unnecessary fuss. 

There is a security concern also. Unlike mongodb, it is an embedded database, it is very easy to make mistakes and corrupt the database. What stopping anyone to update the `_id` field of a document in a collection with invalid data?

**Comment by rwsbillyang** [comment]
Thank you for your explanation, previously maybe I used different app versions in development, so app reported error.  Now the @Id works well.
