### ISSUE TITLE
Fail: File corrupted

### ISSUE THREAD

**Issue by renanccortes** [dizitart/nitrite-database#171]
Hello! 
I am having a problem opening a database that has been corrupted, apparently without any power outage or something similar, the bank is about 1GB in size, and the biggest problem is I can not disable auto recovery, and my system gets stuck waiting for the attempts.

Is there any way to at least disable auto recovery? so I can handle the program?

Code: 

`if (db == null || db.isClosed()) {
                // stuck here
                db = Nitrite.builder() 
                        .compressed()
                        .filePath(DB_NAME)
                        .openOrCreate("user", "password"); 
            }` 

 
Output:

`Trying version 303716
Fail: File corrupted in chunk 303709, expected page length 4..1536, got 1656839170 [1.4.198/6]
Trying version 303715
Fail: File corrupted in chunk 303709, expected page length 4..1536, got 0 [1.4.198/6]
Trying version 303713
Fail: File corrupted in chunk 303709, expected page length 4..1536, got 0 [1.4.198/6]
Trying version 303712
Fail: File corrupted in chunk 303709, expected page length 4..1536, got 0 [1.4.198/6]
Trying version 303711`

Thank you!

**Comment by anidotnet** [comment]
Could you please provide the full stacktrace here?

**Comment by renanccortes** [comment]
It does not make any mistakes, it only gets stuck trying to open the bank, over and over again, and never ends, the only message I get is these recovery attempts below.

`Tentando abrir banco...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Trying latest version
Fail: File corrupted in chunk 303709, expected page length 4..1536, got 1656839170 [1.4.198/6]
Trying version 303716
Fail: File corrupted in chunk 303709, expected page length 4..1536, got 1656839170 [1.4.198/6]
Trying version 303715
Fail: File corrupted in chunk 303709, expected page length 4..1536, got 0 [1.4.198/6]
Trying version 303713
Fail: File corrupted in chunk 303709, expected page length 4..1536, got 0 [1.4.198/6]
Trying version 303712
Fail: File corrupted in chunk 303709, expected page length 4..1536, got 0 [1.4.198/6]
Trying version 303711
Fail: File corrupted in chunk 303709, expected page length 4..1536, got 0 [1.4.198/6]
Trying version 303710
Fail: File corrupted in chunk 303693, expected page length 4..768, got 0 [1.4.198/6]
Trying version 303707
Fail: File corrupted in chunk 303693, expected page length 4..768, got 0 [1.4.198/6]
Trying version 303706
Fail: File corrupted in chunk 303693, expected page length 4..768, got 0 [1.4.198/6]
Trying version 303703
Fail: File corrupted in chunk 303683, expected page length 4..1024, got 0 [1.4.198/6]
Trying version 303702
Fail: File corrupted in chunk 303683, expected page length 4..1024, got 0 [1.4.198/6]
Trying version 303701
Fail: File corrupted in chunk 303683, expected page length 4..1024, got 0 [1.4.198/6]
Trying version 303700
Fail: File corrupted in chunk 303683, expected page length 4..1024, got 0 [1.4.198/6]
Trying version 303699
Fail: File corrupted in chunk 303683, expected page length 4..1024, got 0 [1.4.198/6]
Trying version 303697
Fail: File corrupted in chunk 303683, expected page length 4..1024, got 0 [1.4.198/6]
Trying version 303696
Fail: File corrupted in chunk 303683, expected page length 4..1024, got 0 [1.4.198/6]
Trying version 303689
Fail: File corrupted in chunk 303683, expected page length 4..1024, got 0 [1.4.198/6]
Trying version 303687
Fail: File corrupted in chunk 303683, expected page length 4..1024, got 0 [1.4.198/6]
Trying version 303685
Fail: File corrupted in chunk 303683, expected page length 4..1024, got 0 [1.4.198/6]
Trying version 303683
Fail: File corrupted in chunk 303675, expected page length 4..1024, got 0 [1.4.198/6]
Trying version 303681
Fail: File corrupted in chunk 303675, expected page length 4..1024, got 0 [1.4.198/6]
Trying version 303680
Fail: File corrupted in chunk 303675, expected page length 4..1024, got 0 [1.4.198/6]
Trying version 303679
Fail: File corrupted in chunk 303675, expected page length 4..1024, got 0 [1.4.198/6]
Trying version 303678
Fail: File corrupted in chunk 303656, expected page length 4..1536, got 0 [1.4.198/6]
Trying version 303659
Fail: File corrupted in chunk 303656, expected page length 4..1536, got 0 [1.4.198/6]
Trying version 303658
Fail: File corrupted in chunk 293092, expected page length 4..2048, got 0 [1.4.198/6]
Trying version 303651
Fail: File corrupted in chunk 293092, expected page length 4..2048, got 0 [1.4.198/6]
Trying version 303332`

**Comment by anidotnet** [comment]
I guess you cannot skip recovery as mvstore engine is trying to recover from the corrupted file and AFAIK the library does not have any api to skip this process. The only way out for you I can see is use the recovery method of nitrite before opening it.

`Recovery.recover(<db file name>);`

**Comment by renanccortes** [comment]
This method enters into the same question, does it end does not have timeout to cancel attempts?

**Comment by anidotnet** [comment]
I think it is trying to recover page by page with last known good version and is not retrying the same page over and over again. And as I said there is no way to skip it. The idea is if the file is corrupted, the file can not be used as a reliable database file. So unless the data is recovered, that file cannot be used in mvstore engine thus opened in nitrite.

I'll suggest let the recovery routine run till the end and report back with the final output here. It will take significant amount of time to recover as the file is big.

**Comment by renanccortes** [comment]
Exactly it is not repeating the same page, but it is sendable to run this recovery without even having an estimate, so that it can be shown on the user's screen. Anyway, I will do the process to the end to see what the output will be.

**Comment by anidotnet** [comment]
How did the recovery go?

**Comment by renanccortes** [comment]
Não foi feita a recuperação, devido a urgencia  para a solução foi retirado o banco do sistema. Obrigado pela atenção
