### ISSUE TITLE
project to a sub class

### ISSUE THREAD

**Issue by dustin-auby** [dizitart/nitrite-database#172]
// it will return list of SubEmployee objects containing only some fields
// of Employee object
List<SubEmployee> subEmployeeList
                = repository.find().project(SubEmployee.class).toList();

the above example shows a way to populate only partial fields to an object. the example doesn't really explain how to implement the code though. does the sub object extend the original class, does the sub object need Indices and an @id annotation ?

Thanks,
Dustin

**Comment by dustin-auby** [comment]
also if i had to rather use a collection to use the projection and specified the fields that i wanted to retrieve would it be faster than retrieving all the fields.  from what the code looks like it still performs the full search and then gets the desired fields instead of only getting the desired fields. am i misunderstanding this ? if it is the case that is loads all fields regardless of what i specify is there a way of achieving better performance by only loading specific fields ?

**Still performs full search here**
Cursor cursor = collection.find(lte("birthDay", new Date()),
                sort("firstName", SortOrder.Ascending).thenLimit(0, 3));

// a document with only selected field - 'firstName' and 'lastName'
Document projection = createDocument("firstName", null)
                .put("lastName", null);

**and here gathers the required fields**
// it will return documents containing only 'firstName' and 'lastName'
RecordIterable<Document> documents = cursor.project(projection);

**Comment by anidotnet** [comment]
> does the sub object extend the original class, does the sub object need Indices and an `@Id` annotation ?

Projected class is not an entity. So it does not need indices or id annotations. Here is the implementation - https://github.com/dizitart/nitrite-database/blob/master/nitrite/src/test/java/org/dizitart/no2/objects/data/SubEmployee.java

> also if i had to rather use a collection to use the projection and specified the fields that i wanted to retrieve would it be faster than retrieving all the fields.

You probably misunderstood how the projection works. The search will be performed on the original collection based on the defined indices on main object (here the `Employee` object). Now after you get the result set, if you just only need fewer fields in your business logic, then you can opt for projection. Performance won't matter here it would be same (unless you have a big embedded object in the repository and you skipped it in projection, then you only gain the time required to unmarshall that embedded document).

For more clarification consult the mongodb projection, syntax is different but idea is same.
