### ISSUE TITLE
Nitrite database file - backup in runtime

### ISSUE THREAD

**Issue by perkozki** [dizitart/nitrite-database#175]
im facing problem making copy of nitrite db file in runtime because of lock. 
Spring Boot 2 web flux

Any idea or solution of doing this?

**Comment by anidotnet** [comment]
You do this as follows:

1. In your application, just before the backup, commit everything, halt any CRUD operations and close the db.

2. Use `org.h2.mvstore.MVStoreTool.compact(String sourceFileName, String targetFileName, boolean compress)` to take the backup.

3. Re-open the database and resume CRUD operations.
