### ISSUE TITLE
Filtering on indexed fields with multiple Number only retrieves same type as given Comparable

### ISSUE THREAD

**Issue by tkainrad** [dizitart/nitrite-database#178]
**Situation**

If a field contains multiple different number types, let's say `Integer`s and `Double`s, filtering on these columns will still work if the field is not indexed. For example
```java
Filters.eq(fieldName, new Integer(5));
```
will retrieve also documents that have set a `Double` value that is numerically equal to 5.

However, once the field is indexed, this does no longer work. On indexed fields, only `Document`s using the same type will be retrieved. 

**Question**
Is there any workaround in order to be able to filter on indexed fields that contain multiple `Number` types?

**Proposal**
I believe the filtering behavior should be the same no matter if the field is indexed or not. If it is not possible to retain the superior behavior that exists with non-indexed fields also for indexed fields, this should be pointed out in the documentation.

**Comment by anidotnet** [comment]
The fix is available in latest build - 3.3.0-SNAPSHOT and the repository is - https://oss.sonatype.org/content/repositories/snapshots/org/dizitart/nitrite

Now for both indexed and un-indexed field you have to provide exact number for equality. Behavior is same for both now - 5.0 and 5 is not equal in java, so it is not in nitrite now.

**Comment by tkainrad** [comment]
Thanks for addressing this so quickly!  

I would have preferred if it were possible for both indexed and un-indexed fields. Also in Java it is possible to compare different Number types. This would allow to store different Number types in a field, making use of the schema-less document store and still being able to filter properly.  Now, I basically have to cast everything to double before putting it into Nitrite.

However, I agree that this is a viable solution.
