### ISSUE TITLE
java.lang.UnsatisfiedLinkError: sun.misc.VM.latestUserDefinedLoader0()Ljava/lang/ClassLoader;

### ISSUE THREAD

**Issue by iamkiran** [dizitart/nitrite-database#179]
I am Newbie to the nitrite DB world and exploring the db. I have created a sample rest services API which consumes JSON, based on the user provided json payload I am successfully converting the JSON string to the nitrite document and inserting the same to the db.

When I restart the API services and tyring to insert the document,I'm getting the above error message.

java.lang.UnsatisfiedLinkError: sun.misc.VM.latestUserDefinedLoader0()Ljava/lang/ClassLoader;
	at sun.misc.VM.latestUserDefinedLoader0(Native Method) ~[na:1.8.0_201]
	at sun.misc.VM.latestUserDefinedLoader(Unknown Source) ~[na:1.8.0_201]
	at java.io.ObjectInputStream.latestUserDefinedLoader(Unknown Source) ~[na:1.8.0_201]
	at java.io.ObjectInputStream.resolveClass(Unknown Source) ~[na:1.8.0_201]
	at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source) ~[na:1.8.0_201]
	at java.io.ObjectInputStream.readClassDesc(Unknown Source) ~[na:1.8.0_201]
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[na:1.8.0_201]
	at java.io.ObjectInputStream.readObject0(Unknown Source) ~[na:1.8.0_201]
	at java.io.ObjectInputStream.readObject(Unknown Source) ~[na:1.8.0_201]
	at org.h2.mvstore.type.ObjectDataType.deserialize(ObjectDataType.java:374) ~[h2-mvstore-1.4.197.jar:1.4.197]
	at org.h2.mvstore.type.ObjectDataType$SerializedObjectType.read(ObjectDataType.java:1555) ~[h2-mvstore-1.4.197.jar:1.4.197]
	at org.h2.mvstore.type.ObjectDataType.read(ObjectDataType.java:231) ~[h2-mvstore-1.4.197.jar:1.4.197]
	at org.h2.mvstore.type.ObjectDataType.read(ObjectDataType.java:114) ~[h2-mvstore-1.4.197.jar:1.4.197]
	at org.h2.mvstore.Page.read(Page.java:711) ~[h2-mvstore-1.4.197.jar:1.4.197]
	at org.h2.mvstore.Page.read(Page.java:186) ~[h2-mvstore-1.4.197.jar:1.4.197]
	at org.h2.mvstore.MVStore.readPage(MVStore.java:1936) ~[h2-mvstore-1.4.197.jar:1.4.197]
	at org.h2.mvstore.MVMap.readPage(MVMap.java:698) ~[h2-mvstore-1.4.197.jar:1.4.197]
	at org.h2.mvstore.MVMap.setRootPos(MVMap.java:708) ~[h2-mvstore-1.4.197.jar:1.4.197]
	at org.h2.mvstore.MVStore.openMap(MVStore.java:474) ~[h2-mvstore-1.4.197.jar:1.4.197]
	at org.h2.mvstore.MVStore.openMap(MVStore.java:431) ~[h2-mvstore-1.4.197.jar:1.4.197]
	at org.dizitart.no2.store.NitriteMVStore.openMap(NitriteMVStore.java:89) ~[nitrite-3.1.0.jar:na]
	at org.dizitart.no2.Nitrite.getCollection(Nitrite.java:112) ~[nitrite-3.1.0.jar:na]

**Comment by iamkiran** [comment]
included 3.1.0  jar depedency.

<dependency>
			<groupId>org.dizitart</groupId>
			<artifactId>nitrite</artifactId>
			<version>3.1.0</version>
</dependency>

**Comment by anidotnet** [comment]
Instead of directly using json, try to unmarshal it into a well defined POJO and then store it in nitrite. Use `ObjectRepository` to store the data.

My guess, the reason you are facing the error, is while converting the json directly to a document you might be storing an embedded anonymous class into nitrite, which could not be found later when you restart the service. Unless I see your code I can't be certain.

Meantime, either use `ObjectRepository` with well defined POJO as I mentioned earlier or use `JacksonFacade.parse()` method to parse the json string into a document.

**Comment by iamkiran** [comment]
Feature is pojo class which contains two attribute featureName and featureID.

	private void populateFeatures(Feature feature) throws JsonProcessingException {
		MapperFacade facade = new JacksonFacade();
		NitriteCollection collection = db.getCollection("feature");
		Cursor cursor = collection.find(Filters.eq("featureID", feature.getFeatureId()));
		Document doc = cursor.firstOrDefault();
		if(doc == null) {
			ObjectMapper mapper = new ObjectMapper();
			String featureStringJson =  mapper.writeValueAsString(feature); 
			Document doc1 = facade.parse(featureStringJson);
			WriteResult writeResult = collection.insert(doc1);
			int nitriteId = writeResult.getAffectedCount();
			System.out.println( "nitriteID :" + nitriteId );
			System.out.println(feature.getFeatureId() + " Inserted"); 
		} else {
			System.out.println(feature.getFeatureId() + " already Available");
		}
 }

Please find the sample code snippet.

**Comment by anidotnet** [comment]
Please provide the json and also the pojo class.

**Comment by iamkiran** [comment]
json payload: 

{
	"featureId": "123",
	"featureName": "test123"
}  


public class Feature {

	private String featureId;
	private String featureName;
//getters and setters.
}

**Comment by anidotnet** [comment]
I could not find what seems to be the problem. The below test case ran just fine for me.

```java
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.dizitart.no2.*;
import org.dizitart.no2.filters.Filters;
import org.dizitart.no2.mapper.JacksonFacade;
import org.dizitart.no2.mapper.MapperFacade;

import java.util.Random;

public class Main {

    public static void main(String[] args) throws Exception {
        Random random = new Random(System.currentTimeMillis());
        Nitrite db = Nitrite.builder().filePath("test.db").openOrCreate();
        Feature feature = new Feature();
        feature.setFeatureId("" + random.nextLong());
        feature.setFeatureName("" + random.nextDouble());
        populateFeatures(db, feature);
        showFeatures(db);
    }

    private static void populateFeatures(Nitrite db, Feature feature) throws JsonProcessingException {
        MapperFacade facade = new JacksonFacade();
        NitriteCollection collection = db.getCollection("feature");
        Cursor cursor = collection.find(Filters.eq("featureID", feature.getFeatureId()));
        Document doc = cursor.firstOrDefault();
        if (doc == null) {
            ObjectMapper mapper = new ObjectMapper();
            String featureStringJson = mapper.writeValueAsString(feature);
            Document doc1 = facade.parse(featureStringJson);
            WriteResult writeResult = collection.insert(doc1);
            int number = writeResult.getAffectedCount();
            System.out.println("Entry inserted :" + number);
            System.out.println(feature.getFeatureId() + " Inserted");
        } else {
            System.out.println(feature.getFeatureId() + " error");
        }
    }

    private static void showFeatures(Nitrite db) {
        NitriteCollection collection = db.getCollection("feature");
        Cursor cursor = collection.find(Filters.ALL);
        cursor.forEach(System.out::println);
    }


    public static class Feature {
        private String featureId;
        private String featureName;

        public String getFeatureId() {
            return featureId;
        }

        public void setFeatureId(String featureId) {
            this.featureId = featureId;
        }

        public String getFeatureName() {
            return featureName;
        }

        public void setFeatureName(String featureName) {
            this.featureName = featureName;
        }
    }
}
```

Let me know if you can run above code.

**Comment by anidotnet** [comment]
Any more update on this?

**Comment by iamkiran** [comment]
Thanks you for sharing the valuable feedback, I am able to resolve that issue .

**Comment by iamkiran** [comment]
Hi anidotnet, 

I am sending this payload JSONObject and saving the below record in the DB and when new transaction happens I need to do validation based on elementprimarykey which inturn depends on payloadId
{
	"elementPrimayKey": "payloadId"
	,"payload":{
		"payloadId": "payload12",
		"payloadName": "payload name",
		"payloadStatus": "true"
	}

}

I am using this java code to verify the payloadId is already exist on not in the DB, but i am getting Document doc as null. please provide some assistance. 

String primarykey = (String) feature.get("elementPrimayKey");
			JSONObject payload = feature.getJSONObject("payload");
			NitriteCollection nitritecollection = db.getCollection(collection);
			Cursor cursor = nitritecollection.find(Filters.eq(primarykey, (String) payload.get(primarykey)));
	Document doc = cursor.firstOrDefault();
