### ISSUE TITLE
Filtering does not work if field name contains dot (.) character

### ISSUE THREAD

**Issue by tkainrad** [dizitart/nitrite-database#180]
**Problem**  
If the name of the field that is used for filtering contains a dot character, filtering will not work and retrieve no results at all.

This seems to be because of `DocumentUtils.getFieldValue(Document document, String field)`, which contains the following code:
```java
        Object fieldValue;
        if (field.contains(FIELD_SEPARATOR)) {
            fieldValue = getEmbeddedValue(document, field);
        } else {
            fieldValue = document.get(field);
        }
        return fieldValue;
```
The `FIELD_SEPARATOR` is the dot character. 

**Questions**  
What does the field separator do and why is it necessary? I couldn't find this documented anywhere, am I missing something?

**Proposal**  
If the embedded values are necessary, an idea could be to use a more complex special character sequence instead of a dot character. A . is relatively common and can easily be used as field name by accident.

**Comment by anidotnet** [comment]
`.` as field separator is not uncommon. Mongo uses it. Please avoid having field name with `.`. This character is also not a valid character for java field name. So being a java embedded database it makes perfect sense to have `.` as a field separator.

**Comment by tkainrad** [comment]
Thanks for the clarification! Still think that it could be nice to have this in the documentation though. Personally, I replaced a SQL system with Nitrite and `.` was a very common character in column names to indicate shortened works i.e. `Rel. Number` instead of `Relative Number`.

**Comment by anidotnet** [comment]
In the next major version of nitrite (4.x.x) there will be an option in the builder to set custom field separator. The code is already there in feature-spatial branch. But I don't have any release date for it yet :disappointed: .
