### ISSUE TITLE
3.3.0 Release Date ???

### ISSUE THREAD

**Issue by adhamelia** [dizitart/nitrite-database#184]
@anidotnet 

When you are planning to release 3.3.0 ???  if it's stable then can I build by my self ???

**Comment by anidotnet** [comment]
It is stable currently. No open issues. You can build it yourself.

**Comment by adhamelia** [comment]
I do not see branch or tag of 3.3.0 ??? do I need to use commit point to build 3.3.0 ???

**Comment by anidotnet** [comment]
master contains code for 3.3.0
