### ISSUE TITLE
Any release date planned for version 3.3.0?

### ISSUE THREAD

**Issue by sheinbergon** [dizitart/nitrite-database#188]
@anidotnet  It looks like  all the issues in the milestone are already closed, so is there anything else that keeps you from releasing this version to the public?

**Comment by anidotnet** [comment]
Sorry for the delay. I am currently bogged down so much in my day job that I could not get enough time. I'll try to release it by next week.

**Comment by sheinbergon** [comment]
10x. Let me know if any help is required.

**Comment by sheinbergon** [comment]
@anidotnet Any updates on this release?

**Comment by anidotnet** [comment]
Sorry it has been delayed due to some unforeseen reason from personal front. I'll try to release it by this weekend.

**Comment by anidotnet** [comment]
@sheinbergon version 3.3.0 has been released
