### ISSUE TITLE
About replication: Question

### ISSUE THREAD

**Issue by rokal** [dizitart/nitrite-database#19]
Hello @anidotnet 

I am wondering if I have to the always the format "user-collection@userId"as the name of the replicated collection name? What is the point about that?

Thanks

**Comment by anidotnet** [comment]
You can give any name you want, provided the name is unique for every user, so that one user's data does not get copied into other user's data.

**Comment by rokal** [comment]
Thank you for your quick response. 👍 
I am currently reading about deploying the datagate on heroku (docker is back again).
Is there some additionnal informations I may need to achieve this task with the datagate image in the docker hub?

**Comment by anidotnet** [comment]
Just remember one thing, datagate docker image does not come with mongo in it. So you have to manage your mongo instance separately. Other than that everything should work as it is. Though I have not tried with heroku myself, but if you hit any roadblock, feel free to create an issue here or drop a message in gitter.

I have one request for you, if you like Nitrite, would you be so kind to spread the word? May be write your own success story?

Closing this issue.
