### ISSUE TITLE
Nitrite explorer for Java 7

### ISSUE THREAD

**Issue by asegurpe** [dizitart/nitrite-database#190]
Hello guys,

Firstly, good job with Nitrite and Nitrite-Explorer, is a good database alternative for my needs.

Secondly, I see that nitrite-explorer is coded using Java 8 but I need to intagrate it in Java 7 software, anybody has needed this solution?

Thanks a lot.

**Comment by anidotnet** [comment]
Thanks for the kind words. As for nitrite explorer, it is built using JavaFx 8, so Java 8 is a must. It is not compatible in Java 7. The code logic is pretty simple. You can easily roll your own using Swing which would be better suitable in Java 7.
