### ISSUE TITLE
Security issues in dependency jackson-databind 

### ISSUE THREAD

**Issue by relnah** [dizitart/nitrite-database#195]
There are several CVEs for com.fasterxml.jackson.core:jackson-databind used in nitrite.
https://www.cvedetails.com/version/288511/Fasterxml-Jackson-databind-2.9.8.html

**Comment by anidotnet** [comment]
If you add latest version of Jackson library in your project, nitrite will take the latest library only. If not, you can always exclude these version from nitrite and add latest dependencies in your project.
