### ISSUE TITLE
No get method for @Id field?

### ISSUE THREAD

**Issue by Protoss78** [dizitart/nitrite-database#197]
I've read the documentation and the conversation in this closed issue here: https://github.com/dizitart/nitrite-database/issues/125

I understand the difference between the Id annotated field and the database internal NitriteId. But what I am still wondering is, why is there no convenience method to simply get a document by its defined document id? 

I also could not find any sample on how to find a document by its id. Can you provide an example and add it maybe to the readme?

**Comment by anidotnet** [comment]
To get the NitriteId stored in a document use:

```java
document.getId()
```

And to find a document by it's NitriteId, you can use:

```java
collection.getById(nitriteId)
```

Let me know if you are searching for something else.

**Comment by Protoss78** [comment]
Sorry - I just realized that I formulated my question a little bit misleading. What I want to achieve is the following.
I have a user object where I defined the email as @Id. When I want to check if a specific mail adress is already registered in my database, I have to use the find method with an additional FindOption to check for its existence - here a sample:
`repository.user.find(ObjectFilters.eq("mail", mail), FindOptions.limit(0, 1)).first()`

Would be nice to simply do the following instead:
`repository.user.get(mail)`

**Comment by anidotnet** [comment]
Currently there is no such api as you desire. Even if I expose such a function, the inner working be exactly like - `user.find(ObjectFilters.eq("mail", mail), FindOptions.limit(0, 1)).firstOrDefault()`. 

Moreover, `@Id` is not mandatory in repository. You can use object in repository where there is no id field. In that case, what this api will return?

As I said in issue #125, the `@Id` field does not have any special treatment inside the repository. For your convenience, you can create such an utility method, or if you are using kotlin, you can create an extension method for such requirement.

**Comment by Protoss78** [comment]
Ok. I understand the current functionality. But I have to disagree from a general architectural perspective. What you offer is a NoSQL db without a simple get functionality. What is the point to have an Object collection without @Id field? Especially since you will have an internal _id value anyway? Why hide something from the developer which they will need in the end anyway? I call that a big flaw in your design. You offer a query mechanism without a simple get. I would highly recommend to include that as an enhancement in your next release. 
I tried to use this DB for a very simple use case and failed to do so. I will go back to use SQLite or H2 instead

**Comment by anidotnet** [comment]
I am not claiming the design is suitable for every scenarios, but IMO the functionality you want will be better served by a key-value store. 

Nitrite is a document store like mongo, do you see any such query api in mongo? ObjectRepository is just a built-in ODM layer on top of NitriteCollection. The reason I left the `@Id` field optional, is because of the use case where you don't have any control over the entity object and you can't modify it.

I'll try to see what I can accommodate in ObjectRepository in future with respect to the get call by id field without breaking existing scenarios, but at the end of the day you are always free to choose any solution that fits your requirement.
