### ISSUE TITLE
Building an application over datagate

### ISSUE THREAD

**Issue by TareqK** [dizitart/nitrite-database#198]
Heya! So im wondering, is there some way I can import datagate into my backend project and expand some of its endpoints (stuff like auto sign up, user sync with ldap, write to user repositories via a web interface and have the clients synced, etc), or would i have to integrate via the rest api/database?

**Comment by anidotnet** [comment]
The datagate project was not built as a library project. I would suggest, modify the project at your will and build your own application on top of it.

And lastly, I would highly appreciate if you can contribute any useful feature or fix you develop back in the datagate project.
