### ISSUE TITLE
Crash on app install

### ISSUE THREAD

**Issue by br750** [dizitart/nitrite-database#199]
Hello , at the first install app crash with : 
`Caused by: org.dizitart.no2.exceptions.UniqueConstraintException: NO2.10002: unique key constraint violation for id`

if I relunch app it's OK 

my Pojo (I use jackson too)
```java
public class Chantier implements Serializable {

    @Id
    @JsonProperty("id")
    public int id;

    @JsonProperty("nom")
    public String nom;

    @JsonProperty("ouvrages")
    public ArrayList<Ouvrage> ouvrages;

    @JsonIgnore
    public Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @Override
    public String toString() {
        return "Chantier{" +
                "id='" + id + '\'' +
                ", nom='" + nom + '\'' +
                ", ouvrages=" + ouvrages +
                '}';
    }

}
```
the call :
 
```java
public static  Cursor<Chantier> getChantiers(Context context){

        if(INSTANCE == null ){
            // create/open a database
            INSTANCE  = Nitrite.builder()
                    .compressed()
                    .filePath(context.getFilesDir().getPath() + "/blard.db")
                    .openOrCreate();
        }

        // create an object repository
        ObjectRepository<Chantier> chantierStore = INSTANCE.getRepository(Chantier.class);
        Cursor<Chantier> cursor = chantierStore.find();
        return cursor;
    }
```

this line cause the crash at first install : 
`ObjectRepository<Chantier> chantierStore = INSTANCE.getRepository(Chantier.class);`

thanks , and congratulation for sharing this work ;-)

**Comment by anidotnet** [comment]
Unfortunately, I could not reproduce the issue you said from the given detail. 

The error code only appears, when you already have some data in the repository and later you have added the `@Id` annotation to the object. At that time during opening of the repository, it tries to build the new id index and found duplicate id value. So somehow you need to get rid of the duplicate id value first from the old data before you modify your pojo to add `@Id` annotation.

If this is not the case, then please provide a complete reproducible code, so that I can figure out what is the issue with the code.

**Comment by br750** [comment]
Hello, Thank for your help.
OK !!! May be i have find it , when i use a file to persist , this file is not delete when I remove the app ? So when i re-install app , i get duplicate id .

**Comment by anidotnet** [comment]
Yes that may very well be the case. So I'll suggest instead of insert, you use update with upsert boolean flag as true. In this case, if the id exists, it will update otherwise insert the element.

**Comment by br750** [comment]
There is a way to know if repository exist ? 
It's strange cause it crash on :
`ObjectRepository<Chantier> chantierStore = INSTANCE.getRepository(Chantier.class);`
on install before any insert.

**Comment by anidotnet** [comment]
There is a method `Nitrite.hasRepository()` to check if repository exists. Can you at least provide me with full stacktrace and reproducible code? There is something wrong with your setup otherwise it should not throw exception at the point you mentioned.

**Comment by br750** [comment]
ok 
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.blard.blard/com.blard.blard.MainActivity}: org.dizitart.no2.exceptions.UniqueConstraintException: NO2.10002: unique key constraint violation for id
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6257)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
     Caused by: org.dizitart.no2.exceptions.UniqueConstraintException: NO2.10002: unique key constraint violation for id
        at org.dizitart.no2.internals.IndexingService.buildIndexInternal(IndexingService.java:353)
        at org.dizitart.no2.internals.IndexingService.rebuildIndex(IndexingService.java:312)
        at org.dizitart.no2.internals.IndexingService.createIndex(IndexingService.java:80)
        at org.dizitart.no2.internals.NitriteService.createIndex(NitriteService.java:225)
        at org.dizitart.no2.internals.DefaultNitriteCollection.createIndex(DefaultNitriteCollection.java:74)
        at org.dizitart.no2.objects.DefaultObjectRepository.createIndexes(DefaultObjectRepository.java:315)
        at org.dizitart.no2.objects.DefaultObjectRepository.initRepository(DefaultObjectRepository.java:300)
        at org.dizitart.no2.objects.DefaultObjectRepository.<init>(DefaultObjectRepository.java:57)
        at org.dizitart.no2.objects.RepositoryFactory.open(RepositoryFactory.java:46)
        at org.dizitart.no2.Nitrite.getRepository(Nitrite.java:140)
        at com.blard.blard.library.DataBaseHelper.getChantiers(DataBaseHelper.java:61)
        at com.blard.blard.MainActivity.onCreate(MainActivity.java:132)
        at android.app.Activity.performCreate(Activity.java:6666)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)`

the classe helper for nitrite  where i icall getChantier :
`package com.blard.blard.library;

import android.content.Context;
import android.provider.ContactsContract;

import com.blard.blard.modeles.Chantier;

import org.dizitart.no2.Nitrite;
import org.dizitart.no2.filters.Filters;
import org.dizitart.no2.objects.Cursor;
import org.dizitart.no2.objects.ObjectFilter;
import org.dizitart.no2.objects.ObjectRepository;
import org.dizitart.no2.objects.filters.ObjectFilters;

import java.util.ArrayList;

import static org.dizitart.no2.objects.filters.ObjectFilters.eq;

/**
 *  NITRITE doit être encapsulé dans un singleton pour eviter les erreur
 *  Nitrite support mal plusieurs instances
 */
public class DataBaseHelper {

    /** Constructeur privé */
    private DataBaseHelper()
    {}

    /** Instance unique pré-initialisée */
    private static Nitrite INSTANCE = null;

    /** Point d'accès pour l'instance unique du singleton */
    public static Nitrite getInstance(Context context)
    {
        if(INSTANCE == null ){
            // create/open a database
            INSTANCE  = Nitrite.builder()
                    .compressed()
                    .filePath(context.getFilesDir().getPath() + "/blard.db")
                    .openOrCreate();
        }
        return INSTANCE;
    }


    /**
     * recupere la liste des chantiers
     * @return un objet cursor a itérer
     */
    public static  Cursor<Chantier> getChantiers(Context context){

        if(INSTANCE == null ){
            // create/open a database
            INSTANCE  = Nitrite.builder()
                    .compressed()
                    .filePath(context.getFilesDir().getPath() + "/blard.db")
                    .openOrCreate();
        }

        // create an object repository
        ObjectRepository<Chantier> chantierStore = INSTANCE.getRepository(Chantier.class);
        Cursor<Chantier> cursor = chantierStore.find();
        return cursor;
    }

    public static  void dropChantiers(Context context){

        if(INSTANCE == null ){
            // create/open a database
            INSTANCE  = Nitrite.builder()
                    .compressed()
                    .filePath(context.getFilesDir().getPath() + "/blard.db")
                    .openOrCreate();
        }

        // create an object repository
        ObjectRepository<Chantier> chantierStore = INSTANCE.getRepository(Chantier.class);
        chantierStore.drop();


    }
}
`
the model : 

`package com.blard.blard.modeles;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import org.dizitart.no2.objects.Id;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;


@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonPropertyOrder({
        "id",
        "nom"

})
public class Chantier implements Serializable {

    @Id
    @JsonProperty("id")
    public int id;

    @JsonProperty("nom")
    public String nom;

    @JsonProperty("ouvrages")
    public ArrayList<Ouvrage> ouvrages;

    @JsonIgnore
    public Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @Override
    public String toString() {
        return "Chantier{" +
                "id='" + id + '\'' +
                ", nom='" + nom + '\'' +
                ", ouvrages=" + ouvrages +
                '}';
    }

}
`

the call in main activity : 
`Cursor<Chantier> chantiersCursor = DataBaseHelper.getChantiers(MainActivity.this);`

thanks

**Comment by br750** [comment]
Normally when i uninstall app Nitrite file create like this : 
`INSTANCE  = Nitrite.builder()
                    .compressed()
                    .filePath(context.getFilesDir().getPath() + "/blard.db")
                    .openOrCreate();`
 must gone , cause it's on internal storage (getFilesDir())
Finally it stay after uninstall app and it is present on install ???

**Comment by br750** [comment]
I will fall crazy ;-). I delete the application, so the registration file for nitrite is deleted. I checked that the file was deleted. On a new instalation of the application, it crashes (violation Id), if I restart it, without inserting a new object, I find my old objects. are the repository objects written in the same files? do they stay in memory? I do not understand where they stand.

thanks

**Comment by br750** [comment]
I delete the application, and  the registration file for nitrite is not deleted. 
For path i'm using :
`filePath(context.getFilesDir().getPath() + "/blard.db")`
thanks

**Comment by anidotnet** [comment]
Please provide the code where you have used your `DataBaseHelper`, your `com.blard.blard.MainActivity` and other relevant code.

**Comment by br750** [comment]
sorry 
it's following

Mainactivity
` @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        sharedPreferences  = getApplicationContext().getSharedPreferences("DATA", Context.MODE_PRIVATE);

        String pth = MainActivity.this.getFilesDir().getPath() + "/blard.db";

        /*File file = new File(pth);
        Boolean result = false;
        if(file.exists()){
            result = file.delete();
        } else{
            String y = "NOOOOOO";
        }*/

            // on check chantier collection exists
            Cursor<Chantier> chantiersCursor = DataBaseHelper.getChantiers(MainActivity.this);
            // créer des chantiers
            CreateGoodies createGoodies = new CreateGoodies(MainActivity.this);
            if(chantiersCursor.size() < 1  ){
                createGoodies.createChantier(R.raw.demo);
                createGoodies.createChantier(R.raw.chantier1);
                createGoodies.createChantier(R.raw.chantier2);
                createGoodies.createChantier(R.raw.chantier3);
                createGoodies.createChantier(R.raw.chantier4);
                createGoodies.createChantier(R.raw.chantier5);
                createGoodies.createChantier(R.raw.chantier6);
            }

            // delete les chantiers
            //createGoodies.dropChantiers();


                // on se dirige vers la page d'acceuil
                Intent intent =  new Intent(MainActivity.this,NavigationActivity.class);
                startActivity(intent);
            

        }

    }`

databaseHelper
`public class DataBaseHelper {

    /** Constructeur privé */
    private DataBaseHelper()
    {}

    /** Instance unique pré-initialisée */
    private static Nitrite INSTANCE = null;

    /** Point d'accès pour l'instance unique du singleton */
    public static Nitrite getInstance(Context context)
    {
        if(INSTANCE == null ){
            // create/open a database
            INSTANCE  = Nitrite.builder()
                    .compressed()
                    .filePath(context.getFilesDir().getPath() + "/blard.db")
                    .openOrCreate();
        }
        return INSTANCE;
    }


    /**
     * recupere la liste des chantiers
     * @return un objet cursor a itérer
     */
    public static  Cursor<Chantier> getChantiers(Context context){

        // create an object repository
        ObjectRepository<Chantier> chantierStore = DataBaseHelper.getInstance(context).getRepository(Chantier.class);
        Cursor<Chantier> cursor = chantierStore.find();
        return cursor;
    }

    public static  void dropChantiers(Context context){



        // create an object repository
        ObjectRepository<Chantier> chantierStore = DataBaseHelper.getInstance(context).getRepository(Chantier.class);
        chantierStore.drop();


    }

    public static  void dropChantiersById(Context context,int id){



        // create an object repository
        ObjectRepository<Chantier> chantierStore = DataBaseHelper.getInstance(context).getRepository(Chantier.class);
        chantierStore.remove(eq("id", id));


    }


    public static void updateChantier(Context context,Chantier chantier){


        // create an object repository
        ObjectRepository<Chantier> chantierStore = DataBaseHelper.getInstance(context).getRepository(Chantier.class);

        chantierStore.update(chantier);



    }
`

CreateGoodies
`public class CreateGoodies {

    private static final String LOG_TAG = "blard-" + CreateGoodies.class.getSimpleName();

    private Context context;
    private Nitrite db = null;
    private ObjectRepository<Chantier> chantierStore;

    public CreateGoodies(Context context) {
        this.context = context;
        // create/open a database
       db = DataBaseHelper.getInstance(context);

        // create an object repository
        chantierStore = db.getRepository(Chantier.class);

        // observe any change to the repository
        chantierStore.register(new ChangeListener() {
            @Override
            public void onChange(ChangeInfo changeInfo) {
                // your logic based on action
                Log.i(LOG_TAG,changeInfo.toString());
            }
        });


    }

    public void createChantier(int resourceFile){
        // read json from stream in resource

        InputStream inputStream = context.getResources().openRawResource(resourceFile);
        String jsonString = new Scanner(inputStream).useDelimiter("\\A").next();

        // convert to object Ouvrage
        final ObjectMapper mapper = new ObjectMapper();

        try {
            Chantier chantier = mapper.readValue(jsonString,Chantier.class);
            Log.i(LOG_TAG,"Chantier : "+chantier);

            // insert en base chanteir object
            // insert the employee object
            chantierStore.insert(chantier);


        } catch (JsonProcessingException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }


    public void dropChantiers(){
        DataBaseHelper.dropChantiers(context);
    }


    public Cursor<Chantier> getChantier(){

        Cursor<Chantier> cursor = chantierStore.find();

        return cursor;
    }
}`

Model
`public class Chantier implements Serializable {

    @Id
    @JsonProperty("id")
    public int id;

    @JsonProperty("nom")
    public String nom;

    @JsonProperty("ouvrages")
    public ArrayList<Ouvrage> ouvrages;

    @JsonIgnore
    public Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @Override
    public String toString() {
        return "Chantier{" +
                "id='" + id + '\'' +
                ", nom='" + nom + '\'' +
                ", ouvrages=" + ouvrages +
                '}';
    }

}
`
thanks

**Comment by anidotnet** [comment]
Sorry I could not reproduce the error with your code. Meantime, please provide details for

```java
createGoodies.createChantier(R.raw.demo);
createGoodies.createChantier(R.raw.chantier1);
createGoodies.createChantier(R.raw.chantier2);
createGoodies.createChantier(R.raw.chantier3);
createGoodies.createChantier(R.raw.chantier4);
createGoodies.createChantier(R.raw.chantier5);
createGoodies.createChantier(R.raw.chantier6);
```

and the file `NavigationActivity` if it has anything significant.

**Comment by br750** [comment]
Hello , sorry for the delay 
[raw.zip](https://github.com/dizitart/nitrite-database/files/3969901/raw.zip)
[modeles.zip](https://github.com/dizitart/nitrite-database/files/3969904/modeles.zip)

hope that it's ok , many thanks for help

**Comment by anidotnet** [comment]
Hi @br750 based on your input, I have created the attached demo project. I could not reproduce your error. It is running just fine for me in an x86 emulator. Please find the project in the attachment. 

If you want you can modify the project's code to reproduce the issue and share with me.
[MyApplication.zip](https://github.com/dizitart/nitrite-database/files/3971620/MyApplication.zip)
