### ISSUE TITLE
Sort is slow with Fulltext index

### ISSUE THREAD

**Issue by aespelt** [dizitart/nitrite-database#200]
Regards,

The case is: collection with 65000 docs with fulltext index in 'name' field. Filtering using 'text' is fast (about 40ms) but using sorting is slow (about 3secs in the MacPro). And also we are limiting results to 500. 

Is it normal or can it be a bug or are we missing something?

code:
Nitrite.builder().compressed().filePath("xxx.db").openOrCreate("user","pwd")
createIndex("name", IndexOptions.indexOptions(IndexType.Fulltext))
insert(document)
find(FindOptions.sort(field, SortOrder.Ascending).thenLimit(0, 500))

Thanks a lot.

**Comment by anidotnet** [comment]
@aespelt what you are getting is normal and the timing for sort does not depend on the limits.
