### ISSUE TITLE
Update/insert nested list within a document

### ISSUE THREAD

**Issue by Gillani0** [dizitart/nitrite-database#206]
Hi, 
This is more like a questions than issue. In my use case I need to update/insert a nested element within a document. However, I'm having issues when during deserialisation process. Considering the following classes (in Kotlin):

```
class Record (val Id: UUID, val type:String,  val employees: List<Employee>):Serializable  

class Employee (val Id:UUID, val name:String, val address:String):Serializable 
 ```

I can simply insert a new record in the repository: 
```val record = Record (UUID.newRandomUUID, listOf(employee1, employee2)) ```
```db.getRepository(Record:class.java).insert(record) ```

However, when I updates the nested record and tries to get the object I've the deserislization error: `Instantiation of [simple type, class com.XXX.Employess] value failed for JSON property Employees` 
```
val updatedEmployeesList = .....
val doc = crateDocument("employees", updatedEmployeesList)
db.getRepository(Record:class.java).update(eq("Id", "some_uuid"),doc)
val getRecord = db.getRepository(Record:class.java).find(eq("Id", "some_uuid"))
```

**Comment by anidotnet** [comment]
For json deserialization, you need to have a default parameterless constructor. If you can change your `Employee class` constructor like below:

`class Employee (var Id:UUID = UUID.randomUUID(), var name:String = "", var address:String = ""):Serializable` it should work. Same goes for `Record` class also.

**Comment by Gillani0** [comment]
Thanks for the quick response. 
Unfortunately I can't change the mutability constraint for the classes since it has been used in the legacy project and can have severe impact. 
Is there any other solution to it? For instance, manually serialisation/deserialisation?

**Comment by anidotnet** [comment]
You can implement `Mappable` interface in the classes. https://www.dizitart.org/nitrite-database/#mappable
