### ISSUE TITLE
Upserting document inserts document with null ID when using NitriteId as @Id

### ISSUE THREAD

**Issue by Double-O-Seven** [dizitart/nitrite-database#207]
Hi there!

I've had a problem with upserting documents. I've had the following Kotlin document:
```kotlin
internal data class StructureDocument(
        @Id val id: NitriteId,
        val data: DataDocument
)
```

The ID was precomputed by me and should therefore not be auto-generated.
I've used an object repository created by ``nitrite.getRepository<StructureDocument>()`` and then I've inserted the document using ``objectRepository.update(document, true)``.
In that case, the document was inserted `null` as ID which is obviously wrong.
The reason for that seems to be a method called `removeIdFields` in `DefaultObjectRepository`. This method removes any `_id` key-value-pair as well as the `idField` _if_ it is of type `NitriteId`.

Now, the interesting thing is that everything works fine, if I replace the `NitriteId` with a simple primitive `Long`. It does not get removed because only `idField`s of type `NitriteId` are being removed:

```kotlin
internal data class StructureDocument(
        @Id val id: Long,
        val data: DataDocument
)
```

I'm a bit confused by this inconsistency? What is the expected behaviour?
In my opinion, an upsert should always use the provided ID, if no such document exists.

**Comment by anidotnet** [comment]
You should never generate `NitriteId` value manually or set externally. You should use `@Id val id: NitriteId,` only when you want to capture internally generated `NitriteId`. `@Id` annotation ideally should be used to mark a field as id field with datatype other than `NitriteId`. Here is the doc - https://www.dizitart.org/nitrite-database/#insert
