### ISSUE TITLE
NitriteId uses Long wrapper class instead of primitive long?

### ISSUE THREAD

**Issue by Double-O-Seven** [dizitart/nitrite-database#208]
Is there a specific reason for that?

Also, the following method in `NitriteId` seems rather odd, you can simply return `idValue`:
```java
public Long getIdValue() {
        if (idValue != null) return idValue;
        return null;
    }
```

**Comment by anidotnet** [comment]
I used Long wrapper to avoid storing default 0 value in case of primitive long after deserialization. But for `getIdValue()` you are right, I don't know why I did that, it make no sense :smile: .
