### ISSUE TITLE
Database file encryption

### ISSUE THREAD

**Issue by Gillani0** [dizitart/nitrite-database#209]
Does Nitrite supports DB file encryption as supported by H2 (http://www.h2database.com/html/features.html#file_encryption)?

Our initial experiments shows that the db file contains some plain text of the added info

**Comment by anidotnet** [comment]
At initial stages, there was encryption, but it slows down the db operations significantly, so I removed it later. I'll recommend, encrypt your data wherever required at the object level.

**Comment by Gillani0** [comment]
Alright thanks. Encrypted data at the application level is not a good option since anyone can read the private key from the source code to manually decrypt it (although same can be said for the other file level encryption).
