### ISSUE TITLE
Problem within ObjectFilters.eq("field", "value")

### ISSUE THREAD

**Issue by pysambrero** [dizitart/nitrite-database#21]
when i try this 
`repository.find(ObjectFilters.eq("name", "jhonny")).size() // result = 0 but it should return 3`
it works as expected when I use ObjectFilters.regex instead of ObjectFilters.eq
`repository.find(ObjectFilters.regex("name", "jhonny")).size() // result = 3 -> GOOD`

PS:he database contains three record with name = "jhonny"
and 
`repository.find(ObjectFilters.eq("name", "jhonny")).firstOrDefault() // always return null`
all other operations works fine except equality filter!
Could you please help me.

**Comment by anidotnet** [comment]
Can you please post here the insert statements and the entity class?

**Comment by pysambrero** [comment]
Thank you for your response.
This is how I define my Person Class
`@Indices({
        @Index(value = "name", type = IndexType.Fulltext)
})
public class PersonEntity implements Serializable {
    @Id
    private String uuid;
    private String name;
    private PersonEntity friend;
    private Date dateCreated;

    public PersonEntity(String name) {
        this.uuid = UUID.randomUUID().toString();
        this.name = name; 
        this.dateCreated = new Date();
    }

   public void setFriend(PersonEntity friend) {
        this.friend= friend;
    }

    @Override
    public String toString() {
        return "PersonEntity {" +
                "uuid='" + uuid + '\'' +
                ", name='" + name + '\'' +
                ", dateCreated=" + dateCreated +
                '}';
    }
}`

and this is the insertion code:
`PersonEntity p1 = new PersonEntity("jhonny");
PersonEntity p2 = new PersonEntity("jhonny");
PersonEntity p2 = new PersonEntity("jhonny");

Nitrite db = Nitrite.builder().nitriteMapper(new JacksonMapper())
                .compressed().filePath("path/to/database")
                .openOrCreate(config.get("dbuser"), config.get("dbpass"));

ObjectRepository<PersonEntity> repository = db.getRepository(PersonEntity.class);
repository.insert(p1);
repository.insert(p2);
repository.insert(p3);
`

and this is the code that does not work as expected:
`List<PersonEntity> sameNamePeople = repository.find(ObjectFilters.eq("name",name)).toList();
 }`

When I change eq to regex it works.

By the way, this database is great, and very fast, it is also very stable, except for this little strange behavior when dealing with ObjectFilters.eq

**Comment by anidotnet** [comment]
The reason it is not working as you have declared the name field index as **Fulltext** index. If a field is Fulltext indexed, the only filters that can be used are ```regex``` and ```text```. 

Normally people should use Fulltext index on a field which contains large texts like one or more sentences. I believe the index you should use here is **NonUnique** as the field contains only one string value. And your entity class should look like below:

```java
    @Indices({
            @Index(value = "name", type = IndexType.NonUnique)
    })
    private static class PersonEntity {
        @Id
        private String uuid;
        private String name;
        private PersonEntity friend;
        private Date dateCreated;

        public PersonEntity() {
            this.uuid = UUID.randomUUID().toString();
            this.dateCreated = new Date();
        }

        public PersonEntity(String name) {
            this.uuid = UUID.randomUUID().toString();
            this.name = name;
            this.dateCreated = new Date();
        }
    }
```
And it should resolve your issue.

**Comment by pysambrero** [comment]
Thank you @anidotnet 
I did exactly what you said and it works like a charm, the issue is now solved.
I think you should add it in the documentation for upcoming users, because it is not obvious.
Keep going on this great project.
bahut shukriyaa
