### ISSUE TITLE
Read failed with a lot of data

### ISSUE THREAD

**Issue by bgrosman** [dizitart/nitrite-database#214]
Hi,
I use Nitrite via Maven:

	<dependency>
            <groupId>org.dizitart</groupId>
            <artifactId>nitrite</artifactId>
            <version>3.4.1</version>
        </dependency>

When storing up to about 300,000 objects the database works fine, but with 400,000 and more it always fails in the read stage in getRecord function. Sometimes it gets stuck even without an option to debug it, and sometimes I get this error:

`java.lang.IllegalArgumentException: Could not deserialize [-84, -19, 0, 5, 115, 114, 0, 25, 111, 114, 103, 46, 100, 105, 122, 105, 116, 97, 114, 116, 46, 110, 111, 50, 46, 68, 111, 99, 117, 109, 101, 110, 116, 0, 0, 0, 0, 88, 16, 73, 102, 2, 0, 0, 120, 114, 0, 23, 106, 97, 118, 97, 46, 117, 116, 105, 108, 46, 76, 105, 110, 107, 101, 100, 72, 97, 115, 104, 77, 97, 112, 52, -64, 78, 92, 16, 108, -64, -5, 2, 0, 1, 90, 0, 11, 97, 99, 99, 101, 115, 115, 79, 114, 100, 101, 114, 120, 114, 0, 17, 106, 97, 118, 97, 46, 117, 116, 105, 108, 46, 72, 97, 115, 104, 77, 97, 112, 5, 7, -38, -63, -61, 22, 96, -47, 3, 0, 2, 70, 0, 10, 108, 111, 97, 100, 70, 97, 99, 116, 111, 114, 73, 0, 9, 116, 104, 114, 101, 115, 104, 111, 108, 100, 120, 112, 63, 64, 0, 0, 0, 0, 0, 12, 119, 8, 0, 0, 0, 16, 0, 0, 0, 6, 116, 0, 2, 105, 100, 116, 0, 6, 52, 48, 51, 57, 48, 51, 116, 0, 6, 102, 105, 101, 108, 100, 115, 115, 114, 0, 19, 106, 97, 118, 97, 46, 117, 116, 105, 108, 46, 65, 114, 114, 97, 121, 76, 105, 115, 116, 120, -127, -46, 29, -103, -57, 97, -99, 3, 0, 1, 73, 0, 4, 1... [1.4.193/0]`

The test files are attached.

[NitriteTest.zip](https://github.com/dizitart/nitrite-database/files/4516033/NitriteTest.zip)

**Comment by anidotnet** [comment]
Sorry for belated reply. First you have to create paramaterless default constructors for all your pojo classes (Source, Dest, Record). Otherwise, jackson won't be able to deserialize it. After adding those constructor, the test went fine for me. I could not see any more problems in your test code.

Second, I see from stacktrace you are using older version of h2 mvstore library - `[1.4.193/0]`. Ideally the correct version should be 1.4.200. It should come automatically for nitrite 3.4.1. So check your project dependencies and remove older version of h2 mvstore.

![image](https://user-images.githubusercontent.com/696662/80565927-57c6a480-8a0f-11ea-9092-af65f018197d.png)

**Comment by bgrosman** [comment]
Thanks, I ran it with tips and it passed for 400,000 sourcesNumber, but when I ran with 600,000 sourcesNumber is fails because of OutOfMemoryException.

**Comment by bgrosman** [comment]
To be more clear, our purpose is to write during processing and after that reading the data in chunks in order to prevent such errors. The error occurs during iterating the chunk data in the sourceCursor object. Decrease the chunkSize to 50,000, set sourcesNumber to 600,000 and see if the failure is reproduced.

**Comment by anidotnet** [comment]
After setting these numbers I still can't reproduce this issue.

```
Duration for saving 600000 sources: 59238 ms
Duration for adding 50 dests to 600000 sources: 1824973 ms
Duration for reading all records with dests for 600000 sources: 750679 ms
Duration for reading all fields of 600000 sources: 827468 ms
Duration for closing storage: 9 ms
```

You should use a profiler and find out where the memory leak is happening. That will give you a better idea.

**Comment by bgrosman** [comment]
I just needed to increase the memory for the test and it passed. Thank you!
