### ISSUE TITLE
can ChangeInfo of ObjectRepository's ChangeListener  renturn typed instance ？  

### ISSUE THREAD

**Issue by ylyxf** [dizitart/nitrite-database#218]
like the code blow:
<pre>
repository.register(new ChangeListener() {
			@Override
			public void onChange(ChangeInfo changeInfo) {
				if (ChangeType.INSERT == changeInfo.getChangeType()) {
					Platform.runLater(() -> {
						for (ChangedItem item : changeInfo.getChangedItems()) {
							Sheet newSheet = repository.getById(item.getDocument().getId());
							sheetCardList.add(0, newSheet);
						}
					});
				} 
		        }
});

</pre>

now i get the inserted object by repository.getById (changeInfo can return the document and it's id).
 Is it possible  get the origin inserted object from changeInfo  ?

**Comment by anidotnet** [comment]
No it will only return document. You can covert it to your object, if you have implemented `Mappable` in your object.

**Comment by ylyxf** [comment]
thank you @anidotnet  . i use this code to convert :
<pre>
public static <T> T asObject(Document document, Class<T> type) {
		NitriteMapper nitriteMapper = db.getContext().getNitriteMapper();
		return nitriteMapper.asObject(document, type);
}
</pre>

**Comment by aleksandar-stefanovic** [comment]
IMO this is something that should be expected to be present in the API by default. Or at least with Potassium Nitrate.
