### ISSUE TITLE
ACID transaction

### ISSUE THREAD

**Issue by ibilux** [dizitart/nitrite-database#219]
Hello,
First of all thank you for the amazing work.

What it take to make nitrite database support ACID transaction?

**Comment by anidotnet** [comment]
Thanks @ibilux for your kind words. I decided against it from the very beginning. Moreover, a typical nosql database does not support ACID transaction. 

If you want, you can manage it from your application. As it is an embedded database, to the application nitrite is just a persistent collection.

**Comment by thegarlynch** [comment]
There is a blog that i read, many NoSQL database is now become more transactional
https://blog.yugabyte.com/nosql-databases-becoming-transactional-mongodb-dynamodb-faunadb-cosmosdb/
https://blog.yugabyte.com/6-signs-you-might-be-misunderstanding-acid-transactions-in-distributed-databases/

would like this to become more acid since it is usually used in embedded application

**Comment by anidotnet** [comment]
Transaction support has been added to 4.x branch. It is available now in snapshot repository.

You can use it like below:

```java
TransactionalCollection txCol = collection.beginTransaction(); // or TransactionalRepository<T> txRepo
txCol.insert(documents);
txCol.commit(); // or txCol.rollback();
```

**Comment by anidotnet** [comment]
Now a database wide transaction is supported and earlier transaction api has been removed.

```java
ObjectRepository<TxData> repository = db.getRepository(TxData.class);
repository.createIndex("name", indexOptions(IndexType.Unique));

try (Session session = db.createSession()) {
    Transaction transaction = null;
    try {
        transaction = session.beginTransaction();
        ObjectRepository<TxData> txRepo = transaction.getRepository(TxData.class);

        TxData txData1 = new TxData();
        txData1.setId(1L);
        txData1.setName("John");

        TxData txData2 = new TxData();
        txData2.setId(2L);
        txData2.setName("Jane");

        txRepo.insert(txData1, txData2);

        transaction.commit();
    } catch (TransactionException e) {
        transaction.rollback();
    }
}
```
