### ISSUE TITLE
Multiple filters criteria with one call

### ISSUE THREAD

**Issue by Gillani0** [dizitart/nitrite-database#223]
Hi,

Is it possible to add multiple filter criteria in one go? For example, if there are a set of documents within a repo and I want to query all the documents of `typeOf`--> a list of values ["READ","WRITE"]. 
d1 = ```{"name":"n1","typeOf":"READ","match":"m1"} ```
d1= ```{"name:"n2", "typeOf":"WRITE","match":"m1"}```
d2 = ```{"name":"n3", "typeOf":"UPDATE","match":"m1"}```

I've tried this (in Kotlin):
 ``` 
var filter = and(eq("match", "m1"))
varl list = listOf("READ","WRITE")
for( v in list){
filter = and(filter, eq("typeOf",v))
}

val result = repo.find(filter).toList()
```

However, this only keeps the last value and override the previous one. 
Thanks for your help. Cheers

**Comment by anidotnet** [comment]
Are you looking for `in()` filter? You can find the doc here - https://www.dizitart.org/nitrite-database/#examples

In kotlin, you can do something like

```kotlin
val result = repo.find(("match" eq "m1") and ("typeOf" within arrayOf("READ", "WRITE"))).toList()
```

You need to use potassium-kotlin library. And you can find some examples here - https://github.com/dizitart/nitrite-database/blob/master/potassium-nitrite/src/test/kotlin/org/dizitart/kno2/FilterTest.kt

**Comment by Gillani0** [comment]
@anidotnet Thanks for your quick response.

Just one question, is `when` operator available for the Java API?

**Comment by anidotnet** [comment]
Which `when` operator are you talking about? Kotlin's when?

**Comment by Gillani0** [comment]
Sorry for the late response. What I meant was `within`. Is there any similar operator available for the Java API?

**Comment by anidotnet** [comment]
It is `in()` operator in java api.
