### ISSUE TITLE
Querying list objects with regex

### ISSUE THREAD

**Issue by Gillani0** [dizitart/nitrite-database#224]
Hi,
I need to know if it's possible to add a filter on the list of objects. Consider the following classes

`data class NestedObjects(val ob1:String, val list: List<TempObject>)`

`data class TempObject(val name:String, val aga:Int, val add:LevelUnder)`
`data class LevelUnder(val street:String, val number:Int)`

Then adding such object in the repository 

`val first = NestedObject("value1", listOf(TempObject("name-1", 42,LevelUnder("street", 12) )`

` ObjectRepository.getRepository(NestedObjects::class.java).insert(first )`

Query from the list of 

`val found =  ObjectRepository.getRepository(NestedObjects::class.java).find(elemMatch("list", regex("add.street", ".*?")) `

Currently, I get the error that `add.street` is not a String

Cheers

**Comment by anidotnet** [comment]
I don't know what you are doing wrong, but below test case works fine for me

```kotlin
@Test
    fun testIssue224() {
        val first = NestedObjects("value1", listOf(TempObject("name-1", 42,LevelUnder("street", 12))))
        val repository = db?.getRepository<NestedObjects>()!!
        repository.insert(first)

        val found = repository.find(ObjectFilters.elemMatch("list", ObjectFilters.regex("add.street", ".*?")))
        assertTrue(found.idSet().isNotEmpty())
    }
