### ISSUE TITLE
Nitrite doesn't work with android 7.1.1

### ISSUE THREAD

**Issue by boris-dev** [dizitart/nitrite-database#26]
I want to use your library, but I have an exception on android 7.1.1

Version:
```gradle
compile 'org.dizitart:nitrite:2.0.0'
```

Code:
```java
      String path = Environment.getExternalStorageDirectory().getPath();
      File dbFile = new File(path + "/" + C.DB.DATABASE_FOLDER_NAME + "/" + C.DB.DATABASE_FILE_NAME);
      FileUtils.forceMkdirParent(dbFile);
      if (!dbFile.exists()) {
           dbFile.createNewFile();
      }
      db = Nitrite.builder()
                 .filePath(dbFile.getAbsolutePath())
                 .openOrCreate();`
```

Exception:

```
Caused by: org.dizitart.no2.exceptions.NitriteIOException: NO2.2001: database is already opened in other process
 at org.dizitart.no2.NitriteBuilder.openOrCreateInternal(NitriteBuilder.java:399)
 at org.dizitart.no2.NitriteBuilder.openOrCreate(NitriteBuilder.java:313)
 at ru.adhocapp.vocaberry.repository.UserDataRepository.<init>(UserDataRepository.java:39)
 at ru.adhocapp.vocaberry.repository.CourseWithUserData.withUserData(CourseWithUserData.java:25) 
 at ru.adhocapp.vocaberry.repository.FirebaseRepository$1.onDataChange(FirebaseRepository.java:56) 
```

I will be glad to any help.

**Comment by anidotnet** [comment]
Don't create the db file for yourself

```java
if (!dbFile.exists()) {
    dbFile.createNewFile();
}
```
Instead, try to initialise it as follows:

```java

Nitrite db = Nitrite.builder()
        .filePath(Environment.getExternalStorageDirectory().getPath() + "/" + C.DB.DATABASE_FOLDER_NAME + "/" + C.DB.DATABASE_FILE_NAME)
        .openOrCreate();
```
The ```openOrCreate()``` call will create the db file if it does not exists. But you need to create any parent dir if necessary.

**Comment by boris-dev** [comment]
Thank you, but it doesn't work

**Comment by anidotnet** [comment]
Are you getting the same error after the modification?

**Comment by anidotnet** [comment]
Closing the issue due to inactivity. In case you are able to reproduce the issue after the suggested modification please feel free to reopen the issue.

**Comment by letusdevelop** [comment]
hi Anidotnet, 

I got some exception during the data search. Later I build the new war file and still I get the same error. 
Please advice.

Nitrite nitDB = Nitrite.builder().compressed().filePath(dbFilePath).openOrCreate();
Same error "NO2.2001: database is already opened in other process
Thank you.

**Comment by anidotnet** [comment]
You will get this error when you are trying to create a nitrite instance while another nitrite instance has already opened the database file and acquire an exclusive lock on it. You need to make sure you are not holding any other nitrite instance in some other activities which are not closed yet.

For your reference you can see the example android project and try to understand what I meant here.

**Comment by letusdevelop** [comment]
thank you. can you share the example android project link.

**Comment by anidotnet** [comment]
Here is the link - https://github.com/dizitart/nitrite-database/tree/master/example-android-app
