### ISSUE TITLE
Export all repositories 

### ISSUE THREAD

**Issue by envas** [dizitart/nitrite-database#42]
RepositoryRegistry contains only repositories previously opened using `getRepository()`. It means, that `Export` tool does not write all database entities into the exported json file.

Maybe this is a feature, not a bug, but the question is - how can I export `all` database objects including that not accessed until Export is running?

**Comment by anidotnet** [comment]
Good catch, you are absolutely right. This is a bug and has been introduced recently due to a change.

**Comment by anidotnet** [comment]
Fix should be available in the latest snapshot.
