### ISSUE TITLE
LuceneService.java dosn't work with more than one fulltext index field

### ISSUE THREAD

**Issue by willie68** [dizitart/nitrite-database#44]
[LuceneService.zip](https://github.com/dizitart/nitrite-database/files/1662957/LuceneService.zip)
The text indexing service for lucene do not work with more than one index field. Because for every index field the update method is called. But the update method doesn't update but replaces the already indexed document with the new field. The last field is winning.
Btw. the used lucene version is very old. 
Here i add a more up to date version working with lucene 7.2.1.

[LuceneService.zip](https://github.com/dizitart/nitrite-database/files/1662960/LuceneService.zip)

**Comment by anidotnet** [comment]
The lucene service is an example how one can add external text indexing engine. I did not gave much time to it. Need to look at that what yo are saying. Does your code handle this too?

**Comment by willie68** [comment]
Yes, both. It's using lucene 7.2.1 and handles the updating of the index fields.
For every update index call i try to fetch the already indexed document from lucene and than add the new field to it. For that, i have to store (not only analyse and index) the fields into lucene. Creation of the document field will be with `Field contentField = new TextField(field, text, **Field.Store.YES**);` 
The main issue is with `indexWriter.updateDocument(new Term(CONTENT_ID, jsonId), document);`
because updateDocument will by first delete all documents containing the term and then adding the new one. (See lucene javadoc on updateDocument.)
BTW.: i like nitrite very much...

**Comment by anidotnet** [comment]
Yes now I see it. I have updated my previous comment. Would it be possible for you to create a pull request?

**Comment by willie68** [comment]
pull request created.
