### ISSUE TITLE
Support NitriteId as id field of an object

### ISSUE THREAD

**Issue by anidotnet** [dizitart/nitrite-database#50]
Support auto-generated ```NitriteId``` as an id field in an object.

```java
public class MyClass {
	@Id
	private NitriteId myId;
	private String otherField;
}
```

**Comment by swissfreedev** [comment]
Hi Anindya, 
OK fine. In the meantime, I guess a possible workaround for instance is to store the entities with an autogenerated String (a kind of "GUID") as @Id. As soon as your fix is done, the @Id could be removed then, and the objects would be accessible over their NitriteID.

**Comment by swissfreedev** [comment]
This workaround works fine work all those who have typed entities 
and they don't want to care about autogenerated @Ids:
Just assign a new unique Id while creating an new instance: UUID.randomUUID(); 

```

@Data
public class Touren {

    @Id
    public UUID tourenID;

    public int tourenLegacyID;
    public String tourenName;    
    public String tourenDetail;
    ......
    public Touren(String tourenName, Date tourenDatumvon, Date tourenDatumbis) {              
        tourenID = UUID.randomUUID();  
        this.tourenName = tourenName;
.....
    }
```

**Comment by anidotnet** [comment]
This feature is ready in 2.2.0-SNAPSHOT. Please test it as per your requirement and let me know.

**Comment by swissfreedev** [comment]
fine, I will test it this week end and give you a feedback.
