### ISSUE TITLE
Objects with same @id duplication

### ISSUE THREAD

**Issue by Try4W** [dizitart/nitrite-database#55]
I have such `data class`:
```
data class CaObject(
        @Id val localId: UUID,
        val name: String,
        val icon: CaoIcon,
        val lastInteractionDateTime: LocalDateTime?,
        ...
)
```

And I sometimes upsert values in `ObjectsRepository` like this:
```
    fun put(caObject: CaObject) = Completable.fromCallable {
        repository.update(caObject, true)
    }
```

I don't know in what excact moment or after what exact operation(maybe upsert isn't guilty), but now I have two objects with the same `@Id` in one collection:
```
[CaObject(localId=2deb953a-6218-4ba7-8309-96fca93bfa0d, name=1234, ...),
CaObject(localId=2deb953a-6218-4ba7-8309-96fca93bfa0d, name=1234 ...)]
```

**Comment by anidotnet** [comment]
Sorry, I can't reproduce this. Could you please give me a small reproducible code? Every time I try I am getting 

```
org.dizitart.no2.exceptions.UniqueConstraintException: NO2.10003: unique key constraint violation for localId
```
which is it should be.

**Comment by Try4W** [comment]
Yep, it's definitely nitrit's `@Id`
![image](https://user-images.githubusercontent.com/5736157/36078998-29d6b300-0f8f-11e8-8778-d435b73db9f4.png)

I can share my database file:
[database.zip](https://github.com/dizitart/nitrite-database/files/1714893/database.zip)

It looks like this happened when I changed another repository of another type.

And I cant reproduce it too. Looks like a very strange bug or my mistake. But I can't imagine how I can write two objects with the same id in the same repo :)

**Comment by anidotnet** [comment]
Can you try with 2.2.0-SNAPSHOT? I have provided some fix over indexing on this iteration. Please try with new version and let me know.

**Comment by anidotnet** [comment]
Hold on, I am able to reproduce this issue with this:

```kotlin
@Test
    fun testIssue55() {
        val repository = db?.getRepository<CaObject>()!!
        val uuid = UUID.randomUUID()
        val executor = Executors.newFixedThreadPool(10)
        val latch = CountDownLatch(100)
        for(i in 0..100) {
            val item = CaObject(uuid, "1234")
            executor.submit {
                try{
                    repository.update(item, true)
                } finally {
                    latch.countDown()
                }
            }
        }
        latch.await()
        val cursor = repository.find()
        assertEquals(cursor.size(), 1)
    }
```

working on a fix for it

**Comment by anidotnet** [comment]
Fix is there in latest snapshot -2.2.0-SNAPSHOT. Please try and let me know.

**Comment by Try4W** [comment]
I will try it and will report if this issue will repeat. How can I get the SNAPSHOT?
How should I declare the dependency in buildscript?

**Comment by anidotnet** [comment]
```groovy
buildscript {
    ext {
        nitrite_version = "2.+"
    }
...
}

...
repositories {
        ...
        maven {
            url 'https://oss.sonatype.org/content/repositories/snapshots'
        }
}

compile "org.dizitart:potassium-nitrite:$nitrite_version"
...
```

**Comment by Try4W** [comment]
Sorry, I never tried using SNAPSHOTs. But it seems that it doesn't work:
```
repositories {
    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots'
    }
}

dependencies {
    api 'org.dizitart:potassium-nitrite:2.2.0-SNAPSHOT'
}
```

`Error:Failed to resolve: org.dizitart:potassium-nitrite:2.2.0-SNAPSHOT`

**Comment by anidotnet** [comment]
Can't help you here why it is not resolving for you. Google might help you here also try to check the detailed build log. It is not that hard. See here for an example - https://stackoverflow.com/questions/22175907/cant-import-project-to-android-studio

**Comment by Try4W** [comment]
fixed via moving dependency into root project's build script:

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    }
}
```

It turned out that you need to add a repository for all projects.
