### ISSUE TITLE
Can't specify Index for LocalDateTime

### ISSUE THREAD

**Issue by Try4W** [dizitart/nitrite-database#59]
Hi! My app throws an exception while I declare Index for the field of `LocalDateTime` type.

`NO2.5020: invalid type specified org.threeten.bp.LocalDateTime for indexing`

![image](https://user-images.githubusercontent.com/5736157/37259083-ff53e052-2592-11e8-988d-b555640b3539.png)

While it's superclass implements `Comparable`

![image](https://user-images.githubusercontent.com/5736157/37259091-1f97aa6a-2593-11e8-8c86-d43a6cb42715.png)

**Comment by anidotnet** [comment]
It was not possible due to a validation algo before creating index. This feature should be available now in the latest snapshot.

**Comment by Try4W** [comment]
Still can't do it :(
`NO2.5020: invalid type specified org.threeten.bp.LocalDateTime for indexing`

Snapshot:
`api 'org.dizitart:potassium-nitrite:2.2.0-SNAPSHOT'`

**Comment by anidotnet** [comment]
Sorry I didn't notice earlier. Can't help you with backported api unless Jackson provides a module for it. Jackson serializes this time as an object not a value. And currently nitrite doesn't support indexing on custom pojo.

**Comment by anidotnet** [comment]
May be this can help you - https://github.com/joschi/jackson-datatype-threetenbp
Not sure if it will work or not. Try to extend [KNO2JacksonMapper](https://github.com/dizitart/nitrite-database/blob/master/potassium-nitrite/src/main/kotlin/org/dizitart/kno2/KNO2JacksonMapper.kt) and register the `ThreeTenModule`. And don't forget to set your mapper in `nitrite` builder method.

Let me know how it goes.

**Comment by Try4W** [comment]
Can I write my own module? And somehow implement indexing? Like I wrote my own for serialization/deserialization:

![image](https://user-images.githubusercontent.com/5736157/37316905-d1ef93fa-2672-11e8-93c2-aad654691d9e.png)

**Comment by anidotnet** [comment]
Ideally it should work. As long as you can serialize an object to a value via jackson, you can create index on it. Are you not able to after your change?

On another note, I am curious. Kotlin now needs java 8 so you have java.time already available, then why are you using backport library?

**Comment by Try4W** [comment]
Because Android is tricky :)

![image](https://user-images.githubusercontent.com/5736157/37329516-3360638a-26af-11e8-99fb-cebe6f5c9b3e.png)

```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/LocalDateTime;
    at eu.cortex.cortexalarm.presentation.routes.AppFrameActivity.onCreate(AppFrameActivity.kt:75)
```

**Comment by anidotnet** [comment]
I have written a test case for your use case with `compile group: 'org.threeten', name: 'threetenbp', version: '1.3.6'`

```kotlin

package org.dizitart.kno2

import com.fasterxml.jackson.core.JsonGenerator
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.databind.*
import com.fasterxml.jackson.databind.module.SimpleModule
import com.fasterxml.jackson.module.kotlin.KotlinModule
import org.dizitart.no2.IndexType
import org.dizitart.no2.mapper.JacksonMapper
import org.dizitart.no2.objects.Id
import org.dizitart.no2.objects.Index
import org.dizitart.no2.objects.Indices
import org.junit.Test
import org.threeten.bp.LocalDateTime
import org.threeten.bp.ZoneOffset
import java.nio.file.Files
import java.nio.file.Paths
import java.util.*

/**
 *
 * @author Anindya Chatterjee
 */
class BackportJavaTimeTest {
    private val dbPath = getRandomTempDbFile()

    @Indices(value = [(Index(value = "time", type = IndexType.NonUnique))])
    data class TestData (
        @Id val id: String = UUID.randomUUID().toString(),
        val time: LocalDateTime
    )

    class ThreeTenBpModule : SimpleModule() {
        override fun setupModule(context: SetupContext?) {
            addDeserializer(LocalDateTime::class.java, object : JsonDeserializer<LocalDateTime>() {
                override fun deserialize(p: JsonParser?, ctxt: DeserializationContext?): LocalDateTime? {
                    val timeStamp = p?.longValue
                    return if (timeStamp == -1L || timeStamp == null) null else {
                        LocalDateTime.ofEpochSecond(timeStamp, 0, ZoneOffset.UTC)
                    }
                }
            })

            addSerializer(LocalDateTime::class.java, object : JsonSerializer<LocalDateTime>() {
                override fun serialize(value: LocalDateTime?, gen: JsonGenerator?, serializers: SerializerProvider?) {
                    if (value == null) {
                        gen?.writeNull()
                    } else {
                        val timeStamp = value.toEpochSecond(ZoneOffset.UTC)
                        gen?.writeNumber(timeStamp)
                    }
                }
            })
            super.setupModule(context)
        }
    }

    @Test
    fun testIssue59() {
        val db = nitrite {
            path = dbPath
            nitriteMapper = object : JacksonMapper() {
                init {
                    objectMapper.registerModule(KotlinModule())
                    objectMapper.registerModule(ThreeTenBpModule())
                    objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
                }
            }
        }

        val repo = db.getRepository<TestData>()
        val testData = TestData(time = LocalDateTime.now())
        repo.insert(testData)
        println(repo.find().firstOrDefault())

        Files.delete(Paths.get(dbPath))
    }
}

```

It is running successfully for me. Not seeing the issue you are describing.

**Comment by Try4W** [comment]
I apologize for the long silence, on the last snapshot it all worked!
