### ISSUE TITLE
Error running datagate

### ISSUE THREAD

**Issue by ariel-lenis** [dizitart/nitrite-database#6]
Hi,

Im triying to run the datagate docker image but i have this error message

root@ubuntu-512mb-tor1-01:/home/server/repo/ci/datagate# docker run -p 9090:8080 --name container-datagate-test datagate-test
container_linux.go:247: starting container process caused "exec: \"./datagate.sh\": permission denied"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"./datagate.sh\": **permission denied**".

**Comment by anidotnet** [comment]
Can you post your docker file here?

**Comment by ariel-lenis** [comment]
Sure!

- I modified the base docker file with the right values

- Generated the file keystore.jks (based in https://docs.oracle.com/cd/E19509-01/820-3503/ggfen/index.html)

- The target docker folder just contains the Dockerfile and the keystore.jks

This is the dockerfile contents:

FROM dizitart/nitrite-datagate

COPY keystore.jks /

## Connection details (Replace with your own values)
ENV DATAGATE_HOST "0.0.0.0"
ENV DATAGATE_HTTP_PORT "8080"
ENV DATAGATE_HTTPS_PORT "8443"
ENV DATAGATE_MONITOR_PORT "9090"
ENV DATAGATE_KEY_STORE "keystore.jks"
ENV DATAGATE_KEY_PASSWORD "s3cret"

## Mongo connection details (Replace with your own values)
ENV DATAGATE_MONGO_HOST "172.17.0.3"
ENV DATAGATE_MONGO_PORT "27017"
ENV DATAGATE_MONGO_USER "root"
ENV DATAGATE_MONGO_PASSWORD "some-password"
ENV DATAGATE_MONGO_DATABASE "target-db"

## Starts the server
ENTRYPOINT [ "./datagate.sh" ]

**Comment by ariel-lenis** [comment]
Also i'm using the commands (inside the dockerfile folder):

```
docker build -t datagate-test .
docker run -p 9090:8080 --name container-datagate-test datagate-test
```

**Comment by ariel-lenis** [comment]
I enter to the docker container with the command

`docker run -it -p 9090:8080 --name container-datagate-test datagate-test /bin/sh`

also i commented the dockerfile line: ENTRYPOINT [ "./datagate.sh" ]

And i found that the datagate.sh have no execution rights!

![image](https://cloud.githubusercontent.com/assets/27330468/26664092/07c11752-465d-11e7-89ba-623e55230ef7.png)

**Comment by anidotnet** [comment]
Hmm that is strange. I'll look into it.

**Comment by anidotnet** [comment]
What is the docker version your using?

**Comment by ariel-lenis** [comment]
Docker version 17.05.0-ce, build 89658be

**Comment by anidotnet** [comment]
One thing you can do now is add this line before entrypoint command in your docker file

```docker
RUN ["chmod", "+x", "./datagate.sh"]
ENTRYPOINT [ "./datagate.sh" ]
```
It will solve this issue. Meantime, I'll update the documentation in the upcoming release. And I'll also change the permission of the sh file during CI build. Does that sound good?

**Comment by ariel-lenis** [comment]
Hi,
I tried with the chmod before the entrypoint line but looks like the entrypoint is executed first (or im doing something wrong)

But, worked in this way:

```
CMD ["chmod", "+x", "datagate.sh"]
CMD ["sh", "datagate.sh" ]
```

**Comment by anidotnet** [comment]
The ENTRYPOINT should not run before the RUN command. I can ran the datagate server with this change. Just want to make sure, did you delete the old image and rebuild it after making these changes? Anyway your change is also more or less same.

**Comment by ariel-lenis** [comment]
Agree, but i tried again with this steps:

- Updated the dockerfile

![image](https

://cloud.githubusercontent.com/assets/27330468/26665139/81315522-4665-11e7-8a82-dd622f8e0bea.png)

- used docker stop to stop the container
- used docker rm to delete the container
- used `docker build -t datagate-test .` to build the image again



I got again:

![image](https://cloud.githubusercontent.com/assets/27330468/26665166/9c656630-4665-11e7-8271-9c0ac910ac3d.png)

**Comment by anidotnet** [comment]
This is really seems strange to me. While building the image from scratch, did you get a step like this?

![image](https://cloud.githubusercontent.com/assets/696662/26665416/1b77fcca-46b7-11e7-8404-29cc8e24740d.png)


Could you please run these commands?

- docker rm -f $(docker ps -a -q)
- docker rmi -f datagate-test 
- docker build -t datagate-test .
- docker run -p 9090:8080 --name container-datagate-test datagate-test

I just need to get to the bottom of the issue.

**Comment by ariel-lenis** [comment]
Sure!

Sorry, I tried with that commands but i got the same issue.

**Comment by anidotnet** [comment]
Just one last thing. Can you try with
```docker
RUN ["chmod", "+x", "./datagate.sh"]
```
instead of
```docker
CMD ["chmod", "+x", "datagate.sh"]
```
Remember the "./" in front of datagate.sh

**Comment by ariel-lenis** [comment]
Yes, that works as expected.
