### ISSUE TITLE
Any way to CRUD items in multipile repositories via one transaction?

### ISSUE THREAD

**Issue by Try4W** [dizitart/nitrite-database#60]
I need a way to safely save/remove multiple strongly-coupled items in multiple repositories.

Any recommendations?

**Comment by anidotnet** [comment]
May be you can use events? Listen to change events of a repository. Once an insert event is created and listened to, insert another pojo in another repository in the event handler. Again listen to another pojo's repository change event and insert some other pojo in some other repo in it's event handler. That way you can create an automatic event chain.

**Comment by anidotnet** [comment]
Do you need anymore discussion on this topic? If not let me know so that I can close this issue.
