### ISSUE TITLE
FindOptions.sort() doesn't return correct values

### ISSUE THREAD

**Issue by ArthurSav** [dizitart/nitrite-database#62]
Hi, when sorting items i don't get all the results back.

```java
ObjectFilter belongsToUser = eq("userId", 1);
FindOptions sortBy = FindOptions.sort("status", SortOrder.Descending)

//Without sorting
nitrate.getRepository(Post.class).find(belongsToUser) // returns 26 items

// With sorting
nitrate.getRepository(Post.class).find(belongsToUser, sortBy) // returns 5 items
```

Using FindOptions.sort should return the exact same items but sorted.

Note that `status` is not unique

**Comment by anidotnet** [comment]
Good find!. Fix is available in latest snapshot - 2.2.0-SNAPSHOT. Let me know if you find any more problem.
