### ISSUE TITLE
JacksonMapper does not find modules needed for Java 8

### ISSUE THREAD

**Issue by EMH333** [dizitart/nitrite-database#68]
When using Jackson you need a couple extra modules for in order to use any features like `java.time.LocalDateTime`. When I add those module dependencies to my project, `JacksonMapper` does not find them/use them. I can override `JacksonMapper` and create my own mapping class, that can include those modules, that works just fine. However, it would be nice to include them automatically. 
The object mapper for Jackson appears to have a method titled, "findAndRegisterModules" which in my testing, finds all Jackson modules and includes them. Could this be the default for `JacksonMapper`? That way when wanting to use Java 8 time functions, all a user has to do is include the extra modules with dependency management of their choice and not extend `JacksonMapper`, which is more complex and has more potential for them to make mistakes(?).
I saw similar issues (#51 and #59 ) however those are dealing with Kotlin and did not appear to carry over to Java.
I would open a pull request, but I am still learning how to contribute on GitHub and wouldn't want to mess anything up. Many thanks!

**Comment by anidotnet** [comment]
No worries. Please go ahead and create a pull request if you are willing, I'll be more than glad for your contribution. Please don't forget to add sufficient test cases also.

Before merging all pull requests in github go through a manual review, so no chance of messing things up :smile:.

**Comment by anidotnet** [comment]
Let me know if you are willing to give the PR.

**Comment by anidotnet** [comment]
No issues, I'll make the necessary changes then.

If you like this project, please do spread the word :smile:

**Comment by anidotnet** [comment]
@EMH333 you can find this feature in the latest snapshot - 3.0.1-SNAPSHOT
