### ISSUE TITLE
Datagate, UnsatisfiedDependencyException

### ISSUE THREAD

**Issue by ariel-lenis** [dizitart/nitrite-database#7]
Hi, after starting the datagate docker image i have a weird exception.

I'm attaching the console output:
[console.txt](https://github.com/dizitart/nitrite-database/files/1043654/console.txt)

**Comment by anidotnet** [comment]
Oops!! my bad. That has happened for some last minute untested changes. Will provide fix in the upcoming release. Meantime you can override the environment variable with this in your docker file

```docker
ENV DATAGATE_SYNC_LOG_CLEANUP_DELAY "30"
```

**Comment by ariel-lenis** [comment]
Thanks!, it worked JIC this is my new console output:
[console2.txt](https://github.com/dizitart/nitrite-database/files/1043740/console2.txt)

Looks like there is a problem with mongo 

> Exception in monitor thread while connecting to server localhost:27017

Is triying to connect to localhost???

**Comment by anidotnet** [comment]
Ahh it's just the MongoAutoConfiguration of spring boot kicks in for monitoring. Your application is connected properly

```
org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:233}] to 172.17.0.3:27017
```
Though it will not stop datagate from running properly, but mongo monitoring will not work. I never tried with mongo instance other than localhost, so never faced this issue. I'll fix this too.
