### ISSUE TITLE
order by using a nullable columns results in an empty cursor

### ISSUE THREAD

**Issue by cpotter1** [dizitart/nitrite-database#72]
If I do an order by with a column that is null, the row is t returned in the cursor.  It should be returned (ideally before the non null fields).

**Comment by anidotnet** [comment]
Can you please put some reproducible code on what are you trying to achieve?

**Comment by cpotter1** [comment]
`public class PureNitriteTest {

  protected static Nitrite db;

  @BeforeClass
  public static void startDb() {
    db = Nitrite.builder()
        .compressed()
        .filePath("build/dbFile")
        .openOrCreate("test", "password");
  }

  @AfterClass
  public static void closeDb() {
    db.close();
  }

  @Test
  public void orderByOnNullableColumn() throws Exception {
    NitriteCollection coll = db.getCollection("test_orderByOnNullableColumn");
    try {
      coll.createIndex("id", IndexOptions.indexOptions(IndexType.Unique));
      coll.createIndex("group", IndexOptions.indexOptions(IndexType.NonUnique));
    } catch (IndexingException e) {
      // ignore
    }

    coll.remove(Filters.ALL);

    Document doc = new Document().put("id", "test-1").put("group", "groupA");
    assertEquals(1, coll.insert(doc).getAffectedCount());

    doc = new Document().put("id", "test-2").put("group", "groupA").put("startTime", DateTime.now());
    assertEquals(1, coll.insert(doc).getAffectedCount());

    Cursor cursor = coll.find(Filters.eq("group", "groupA"), FindOptions.sort("startTime", SortOrder.Descending));
    assertEquals(2, cursor.size());
  }


}`

Failed with this result: "assertEquals(2, cursor.size());":
~~~
expected:<2> but was:<1>
Expected :2
Actual   :1
 <Click to see difference>

java.lang.AssertionError: expected:<2> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)

**Comment by cpotter1** [comment]
Tried on 2.1.1 and 3.0.0; same result.
