### ISSUE TITLE
get an ObjectRepository from a type with an unique identifier

### ISSUE THREAD

**Issue by LarsWerkman** [dizitart/nitrite-database#78]
I'm missing the ability to create a multiple repositories of a single type based on a unique identifier.

**Comment by LarsWerkman** [comment]
[https://github.com/dizitart/nitrite-database/pull/79](url)

**Comment by anidotnet** [comment]
Thank you for the contribution. I have some review comments though.

Could you please add some test cases for the new method you have added?

If you are familiar with kotlin, could you please add the same new method [like this](https://github.com/dizitart/nitrite-database/blob/master/potassium-nitrite/src/main/kotlin/org/dizitart/kno2/Nitrite.kt#L54) and a test case there also? But if you are not, no worries let me know I'll add it.

**Comment by LarsWerkman** [comment]
@anidotnet I will try to get it done this weekend

**Comment by anidotnet** [comment]
Just checking, anymore update on this?

**Comment by LarsWerkman** [comment]
haven't had any time for it yet, but I will work on it soon

**Comment by anidotnet** [comment]
@LarsWerkman just checking, did you get a chance to close this? If you are busy let me know.

**Comment by holgerstolzenberg** [comment]
If there is no forthcoming in the next days, is it possible to skip this issue to `3.0.2`? 

I am very interested in getting a release with the optional shutdown hook that is not a `-SNAPSHOT` version. This is somewhat crucial for my integration of Nitrite in a spring-boot app that triggers the shutdown via `@PreDestroy`.

**Comment by anidotnet** [comment]
Sure

**Comment by anidotnet** [comment]
@holgerstolzenberg We had a release yesterday - 3.0.1, which contains optional shutdown hook.

**Comment by holgerstolzenberg** [comment]
Thanks, already adopted it!

**Comment by anidotnet** [comment]
@LarsWerkman changes are available in 3.1.0-SNAPSHOT
