### ISSUE TITLE
Error accessing datagate portal

### ISSUE THREAD

**Issue by ariel-lenis** [dizitart/nitrite-database#8]
After starting the datagate docker image with the command:

`docker run -p 8080:8080 -p 8443:8443 -p 9090:9090 --name container-test test`

I cant access to the portal with any of the used ports:

![image](https://cloud.githubusercontent.com/assets/27330468/26666454/00ff6250-466e-11e7-9eee-224545ab18b7.png)

![image](https://cloud.githubusercontent.com/assets/27330468/26666465/098f1eba-466e-11e7-83f8-ef6c6611fc76.png)

![image](https://cloud.githubusercontent.com/assets/27330468/26666474/181a83d4-466e-11e7-90cc-6545f9a58916.png)

**Comment by anidotnet** [comment]
Try with this url -  http://localhost:8080/datagate

**Comment by ariel-lenis** [comment]
Cool!!! thanks a lot!

![image](https://cloud.githubusercontent.com/assets/27330468/26666782/c96de148-466f-11e7-962f-21791b80e425.png)

**Comment by anidotnet** [comment]
Excellent. Closing this issue now.
