### ISSUE TITLE
Annotations for POJO Documentation

### ISSUE THREAD

**Issue by yemikudaisi** [dizitart/nitrite-database#81]
Trying out nitrite for the first time. I've decided to stick to POJO as I already have existing entity classes. However, the following annotations in you examples doesn't seem to work. I kept getting this error `@org.dizitart.no2.objects.Index is missing a default value for the element 'value'`

```java
@Indices({
        @Index(field = "joinDate", type = IndexType.NonUnique),
        @Index(field = "name", type = IndexType.Unique)
})
```

So I took a look into you source code and realized the correct field is supposed to be **`value`** in place of **`field`**. So below was what worked at the end of the day. I just thought it was worth mentioning considering the documentation is misleading.

```java
@Indices({
        @Index(value = "joinDate", type = IndexType.NonUnique),
        @Index(value = "name", type = IndexType.Unique)
})
```

**Comment by anidotnet** [comment]
Thanks for pointing it out. When I have changed the name in annotations, for got to update the doc. I'll fix it in next iteration.

**Comment by anidotnet** [comment]
Fixed. Read me is updated. The doc site will be updated in next release.
