### ISSUE TITLE
Get single document from a specific collection

### ISSUE THREAD

**Issue by sarankup** [dizitart/nitrite-database#82]
Hi,

Please advise how to get a single document from a collection by key and value pairs. I see the document to find the repository or by cursor. Is there any function to find first instance by key and value.

For example as follows
`Document soneDocument = collection.find(eq("username", data.getUserName())).firstOrDefault();`

**Comment by anidotnet** [comment]
Can you please elaborate what you are trying to achieve using some pseudo code? And what do you mean by **get a single document from a collection by key and value pairs**? `eq("username", data.getUserName())` is the query operator for key and value.

If you are looking for something like
```java
collection.findFirst(new KeyValuePair<String, String>("name", "Saravanan"));
```
then no. Nitrite does not have any method like that, but it is not harder to roll your own either. Else, you have to find it like you said:

```java
Document someDocument = collection.find(eq("name",  "Saravanan")).firstOrDefault();
```
