### ISSUE TITLE
Make runtime shutdown hook optional

### ISSUE THREAD

**Issue by flqw** [dizitart/nitrite-database#84]
Hi,

i'm using the db in a spring boot application with a complex shutdown cycle. I have placed the close() command exactly where i want it, but the runtime shutdown hook registered in the builder

https://github.com/dizitart/nitrite-database/blob/ad304b5ade803b012af089f53e1f7ead14da2cd3/nitrite/src/main/java/org/dizitart/no2/NitriteBuilder.java#L475

fires before that, what leads to some unwanted data loss. Can you add a method to the builder which disables the registering of the shutdown hook?

Thanks.

**Comment by anidotnet** [comment]
This should be available in latest snapshots.

**Comment by flqw** [comment]
Awesome thanks a lot. Snapshots aren't published to any repository, are they?

**Comment by anidotnet** [comment]
It is published to central maven repository in snapshot channel. Version would be 3.0.1-SNAPSHOT.
