### ISSUE TITLE
Design: Nitrite Clustering / Replication without MongoDB

### ISSUE THREAD

**Issue by andrewfinnell** [dizitart/nitrite-database#85]
One of the key advantages of being able to use Nitrite is it's embedded nature. Replication is crucial in an environment where Eventual Consistency is acceptable. However, relying on MongoDB seems to be counter intuitive when it comes to using a product like Nitrite. If there was already access to a MongoDB instance, what value is Nitrite adding at this point? Is there a Use Case being missed?

I propose the following enhancements:

- Allow Nitrite to run in a clustering mode, with both write-back and write-ahead options
- Allow Nitrite's Replication to function using peer-to-peer replication instead of relying on a separate MongoDB instance.

**Comment by anidotnet** [comment]
Nitrite is ideal for disconnected devices which are not always online. When you want to replicate data between such devices, it is an easy and proven solution to have a server-client architecture to facilitate the replication and take care of locking, conflict resolution etc on the way. Moreover having an always on server with latest replica of the data makes the replication very easy and fast. CouchDb follows similar pattern for replication.

Nitrite does not depends on mongodb. Replication is an addon feature for nitrite. When you need replication you fire up a nitrite datagate server which takes care of the logic for you. Datagate server uses mongodb as a replica storage which can be replaced by any storage system even by another nitrite instance on the server. Moreover nitrite supports selective replication, you can chose which collection to replicate and which ones to ignore. Datagate will store and replicate data for those collections only.

I get your point regarding the access to mongodb. But it's not always the case that if you have access to a remote mongodb instance you don't need to store data locally in your device. A typical use case is email client. You want to store bulk of the data offline in the device which you don't want to replicate. But you want to replicate your account settings and here nitrite's selective replication comes into rescue. But again it is an addon feature, in most of the cases I see users tend to use nitrite as a local storage only and they use their own replication mechanism via some web api.

Having said that, I find your proposal interesting and I think it will make nitrite useful in some specific use cases. But truth to be told, I have very very limited knowledge on p2p networking let alone replication over it. Would you be interested to contribute?
