### ISSUE TITLE
improper handling of attribute removal

### ISSUE THREAD

**Issue by cpotter1** [dizitart/nitrite-database#87]
using 3.0.0:

```java
  @Test
  public void updateAfterAttributeRemoval() throws Exception {
    NitriteCollection coll = db.getCollection("test_updateAfterAttributeRemoval");
    coll.remove(Filters.ALL);

    Document doc = new Document().put("id", "test-1").put("group", "groupA");
    assertEquals(1, coll.insert(doc).getAffectedCount());

    Document savedDoc1 = coll.find().firstOrDefault();
    assertNotNull(savedDoc1);

    Document clonedDoc1 = new Document(savedDoc1);
    assertEquals(savedDoc1, clonedDoc1);

//    clonedDoc1.put("group", null);
    clonedDoc1.remove("group");
    assertEquals(1, coll.update(clonedDoc1).getAffectedCount());

    Document savedDoc2 = coll.find(Filters.ALL).firstOrDefault();
    assertNotNull(savedDoc2);
    assertNull(savedDoc2.get("group"));
  }
```

fails:
expected null, but was:<groupA> (last assert)

**Comment by anidotnet** [comment]
This is working as expected. When you remove `group` attribute, they key will also be removed from the doc. Now when you use `clonedDoc1` to update the collection, there is nothing to update for `group` as there is no such key present in the `clonedDoc1`. So the previous value of `group` will remain in the doc which is there in the collection. Remember, you are not removing the `group` field from the doc inside the collection.

But if you change your code as below
```java
clonedDoc1.put("group", null);
//clonedDoc1.remove("group");
```
then it will update the `group` field in the collection with `null` and your test passes.
