### ISSUE TITLE
ObjectRepository autogenerated id

### ISSUE THREAD

**Issue by dipacs** [dizitart/nitrite-database#88]
Helo,

I had some trouble using the Object repository. I want to use auto generated Id-s (anyway) but i can't.

I tryed:
- @id long id; -> id will allways null and allways updates the first insert (with upsert)
- @Id Long id; -> id can not be null exception
- @Id NitriteId id; -> id field can not be null
- @Id NitriteId id = NitriteId.createNew() -> Id field isn't saved
- No id at all -> Object must have an id field exception.

I'm out of ideas. What is the preferred way to achive auto generated id-s using Object repository?

Thanks, David

**Comment by anidotnet** [comment]
Please have a look at this test class [NitriteIdAsIdTest](https://github.com/dizitart/nitrite-database/blob/master/nitrite/src/test/java/org/dizitart/no2/objects/NitriteIdAsIdTest.java)
